$axure.loadCurrentPage({
  "url":"media.html",
  "generationDate":new Date(1378338555900.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dacb86f2f9a7499a96b19a7ca8387bca",
    "type":"Axure:Page",
    "name":"Media",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"abe445b3f6e14d849c6d55f67082cb10",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"3854eed9bc0949e584609e7e5d5a678d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":108},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ca1e76153f426c8eb7a878d2a6583a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":108},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1140e715fd294dd5aee643264894bbf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":150,
              "y":108},
            "size":{
              "width":129,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413cf40677174047956b0460451d1a0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":150,
                  "y":108},
                "size":{
                  "width":129,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4731ba67a92c49d7b3cd3d869860a059",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":917}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"1fa512446a0540dca110fe9c661524a5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":141}},
          "adaptiveStyles":{
},
          "masterId":"97ea343fad854646aeb1401045237bb3"}]}},
  "masters":{
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png"}}]}},
    "97ea343fad854646aeb1401045237bb3":{
      "packageId":"97ea343fad854646aeb1401045237bb3",
      "type":"Axure:Master",
      "name":"МЕДИА2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"57532d504d014988868d6bd3833fffa1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e69d2f21cffe49c6b936cae70704d6a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Album in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"album.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"a424e1130f2e4bb492536e86fc083a5e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":491,
                "y":8},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d866d03d0df47ba8d4c3c35ec44485b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":491,
                    "y":8},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"de9125ee706c42e6ac9fbe1780d0f607",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":251,
                "y":8},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"49dc439df5be4e6f8b9c28154ea3a484",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":251,
                    "y":8},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Album in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"album.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/media/u44.png"}},
{
            "id":"a11517a7fbbe48eca9f6d93b4a06d0c5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":731,
                "y":8},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd7cc4f6e39c41b9a98a2866710567d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":731,
                    "y":8},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"76c6b48ebee043e092d1415e584cae3e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":247},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8150cd06efa14796962c98e58dcc3925",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":12,
                    "y":247},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"df67d3214b4a449b900edc438845e9fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":491,
                "y":247},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"06e668a4c9ed411e9738a59f45f91692",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":491,
                    "y":247},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"75ccfd24bf98440d9002a87ccb910c26",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":251,
                "y":247},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa5db229591c44d5aa1f1f35e53f5d50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":251,
                    "y":247},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"e531a8847b5b47f38e39f49c7f5a325a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":731,
                "y":247},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8673d8ee7fe94c6bbc67b834c1b63aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":731,
                    "y":247},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"37436dcce57f40558eb260b9599ac709",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":13,
                "y":486},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b1de3233efb74d9eb5caddf5cff9bf40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":13,
                    "y":486},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"7921424446014a6cab99e4f2409fd9d9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":492,
                "y":486},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df1dc6c16bca4d9292d9c9555075d38b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":492,
                    "y":486},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Album in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"album.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/media/u58.png"}},
{
            "id":"56339341b93f4b0aa699f4b4751a14a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":252,
                "y":486},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"514252e3d4924f019270dbe465a161ec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":252,
                    "y":486},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"5dc4c68a1f0b47c4a7dd8ff562c40e98",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":732,
                "y":486},
              "size":{
                "width":240,
                "height":240}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16b188433dd646be836861a05f52f507",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":732,
                    "y":486},
                  "size":{
                    "width":240,
                    "height":240}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u40.png"}},
{
            "id":"509a97e445a84b02b49bff2229ec1f46",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":251,
                "y":428},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2df440b613de4656b2c09d2d313c42c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":251,
                    "y":428},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"dc17c9c6c0a248ea86735018ee71bc21",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":491,
                "y":188},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd51c95adda04dbfb4a441d799ae0c04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":491,
                    "y":188},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"1e44627d0afd408cb456b61d34cc5e8c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":731,
                "y":188},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"591d514df7494e26b66c0409c941c747",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":731,
                    "y":188},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"0712ed49359b421a9875627a7966dff1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":491,
                "y":428},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c25f291dbd0416f800970ed74b51230",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":491,
                    "y":428},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"bc7afefbb632427ea3942f342b7592f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":731,
                "y":428},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e1761b794184e46912ec1843f121a21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":731,
                    "y":428},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"f57bbb101ab2483da9ef8cf14def3bb5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":732,
                "y":668},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"12dcbefb850d4861bdb1be7516f8db16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":732,
                    "y":668},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"3a694dd8200f4bcd950d347802774052",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":252,
                "y":667},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bf7f372ec2b8476d90c28cd9c8e2a4a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":252,
                    "y":667},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"8fca90d4749446f99e2ae03bc587558b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":12,
                "y":667},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"968721643bcd47749f37744fdde3e097",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":12,
                    "y":667},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"f2878ea9e31444a3897c4b6a14667aa2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":11,
                "y":428},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e1ad0aef97b4401a1dea08438820746",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":11,
                    "y":428},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"940cf17b743e42e9b6f8406badc8967b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":12,
                "y":188},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74350fe8c23d4d3eb73d2c4bb531e71c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":12,
                    "y":188},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Album in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"album.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"9d3cf297649d463187b51c5c0c7cf690",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":492,
                "y":668},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bd13103adb984e9ba9451a4c76d49186",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":492,
                    "y":668},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Album in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"album.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/media/u64.png"}},
{
            "id":"850e952fc53e48b1b86c8a133524f552",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":251,
                "y":188},
              "size":{
                "width":240,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c39db302aaa4565a97dbb3487fe06d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":251,
                    "y":188},
                  "size":{
                    "width":240,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Album in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"album.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/media/u64.png"}}]}}},
  "objectPaths":{
    "abe445b3f6e14d849c6d55f67082cb10":{
      "scriptId":"u0",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u1"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u2"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u3"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u4"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u5"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u6"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u7"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u8"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u9"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u10"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u11"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u12"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u13"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u14"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u15"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u16"}},
    "3854eed9bc0949e584609e7e5d5a678d":{
      "scriptId":"u17"},
    "b4ca1e76153f426c8eb7a878d2a6583a":{
      "scriptId":"u18"},
    "1140e715fd294dd5aee643264894bbf7":{
      "scriptId":"u19"},
    "413cf40677174047956b0460451d1a0c":{
      "scriptId":"u20"},
    "4731ba67a92c49d7b3cd3d869860a059":{
      "scriptId":"u21",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u22"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u23"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u24"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u25"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u26"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u27"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u28"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u29"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u30"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u31"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u32"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u33"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u34"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u35"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u36"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u37"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u38"}},
    "1fa512446a0540dca110fe9c661524a5":{
      "scriptId":"u39",
      "57532d504d014988868d6bd3833fffa1":{
        "scriptId":"u40"},
      "e69d2f21cffe49c6b936cae70704d6a9":{
        "scriptId":"u41"},
      "a424e1130f2e4bb492536e86fc083a5e":{
        "scriptId":"u42"},
      "8d866d03d0df47ba8d4c3c35ec44485b":{
        "scriptId":"u43"},
      "de9125ee706c42e6ac9fbe1780d0f607":{
        "scriptId":"u44"},
      "49dc439df5be4e6f8b9c28154ea3a484":{
        "scriptId":"u45"},
      "a11517a7fbbe48eca9f6d93b4a06d0c5":{
        "scriptId":"u46"},
      "cd7cc4f6e39c41b9a98a2866710567d6":{
        "scriptId":"u47"},
      "76c6b48ebee043e092d1415e584cae3e":{
        "scriptId":"u48"},
      "8150cd06efa14796962c98e58dcc3925":{
        "scriptId":"u49"},
      "df67d3214b4a449b900edc438845e9fa":{
        "scriptId":"u50"},
      "06e668a4c9ed411e9738a59f45f91692":{
        "scriptId":"u51"},
      "75ccfd24bf98440d9002a87ccb910c26":{
        "scriptId":"u52"},
      "aa5db229591c44d5aa1f1f35e53f5d50":{
        "scriptId":"u53"},
      "e531a8847b5b47f38e39f49c7f5a325a":{
        "scriptId":"u54"},
      "8673d8ee7fe94c6bbc67b834c1b63aa9":{
        "scriptId":"u55"},
      "37436dcce57f40558eb260b9599ac709":{
        "scriptId":"u56"},
      "b1de3233efb74d9eb5caddf5cff9bf40":{
        "scriptId":"u57"},
      "7921424446014a6cab99e4f2409fd9d9":{
        "scriptId":"u58"},
      "df1dc6c16bca4d9292d9c9555075d38b":{
        "scriptId":"u59"},
      "56339341b93f4b0aa699f4b4751a14a6":{
        "scriptId":"u60"},
      "514252e3d4924f019270dbe465a161ec":{
        "scriptId":"u61"},
      "5dc4c68a1f0b47c4a7dd8ff562c40e98":{
        "scriptId":"u62"},
      "16b188433dd646be836861a05f52f507":{
        "scriptId":"u63"},
      "509a97e445a84b02b49bff2229ec1f46":{
        "scriptId":"u64"},
      "2df440b613de4656b2c09d2d313c42c8":{
        "scriptId":"u65"},
      "dc17c9c6c0a248ea86735018ee71bc21":{
        "scriptId":"u66"},
      "cd51c95adda04dbfb4a441d799ae0c04":{
        "scriptId":"u67"},
      "1e44627d0afd408cb456b61d34cc5e8c":{
        "scriptId":"u68"},
      "591d514df7494e26b66c0409c941c747":{
        "scriptId":"u69"},
      "0712ed49359b421a9875627a7966dff1":{
        "scriptId":"u70"},
      "2c25f291dbd0416f800970ed74b51230":{
        "scriptId":"u71"},
      "bc7afefbb632427ea3942f342b7592f8":{
        "scriptId":"u72"},
      "0e1761b794184e46912ec1843f121a21":{
        "scriptId":"u73"},
      "f57bbb101ab2483da9ef8cf14def3bb5":{
        "scriptId":"u74"},
      "12dcbefb850d4861bdb1be7516f8db16":{
        "scriptId":"u75"},
      "3a694dd8200f4bcd950d347802774052":{
        "scriptId":"u76"},
      "bf7f372ec2b8476d90c28cd9c8e2a4a8":{
        "scriptId":"u77"},
      "8fca90d4749446f99e2ae03bc587558b":{
        "scriptId":"u78"},
      "968721643bcd47749f37744fdde3e097":{
        "scriptId":"u79"},
      "f2878ea9e31444a3897c4b6a14667aa2":{
        "scriptId":"u80"},
      "6e1ad0aef97b4401a1dea08438820746":{
        "scriptId":"u81"},
      "940cf17b743e42e9b6f8406badc8967b":{
        "scriptId":"u82"},
      "74350fe8c23d4d3eb73d2c4bb531e71c":{
        "scriptId":"u83"},
      "9d3cf297649d463187b51c5c0c7cf690":{
        "scriptId":"u84"},
      "bd13103adb984e9ba9451a4c76d49186":{
        "scriptId":"u85"},
      "850e952fc53e48b1b86c8a133524f552":{
        "scriptId":"u86"},
      "1c39db302aaa4565a97dbb3487fe06d8":{
        "scriptId":"u87"}}}});