$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1378338553014.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b67f515c3944068a92fe0ff03f3405f",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"20823511ad0e40099e6be788f8242b1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":570,
              "y":108},
            "size":{
              "width":190,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f940fde377cc48d096806d8f24501892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":570,
                  "y":108},
                "size":{
                  "width":190,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebd6aad4180a4b06b1242b42fa0fa3a6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":108}},
          "adaptiveStyles":{
},
          "masterId":"d323c5882809487ba803b1c84f4064a2"},
{
          "id":"7597e0502d2a42b7958ac11993fa954f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":571,
              "y":147},
            "size":{
              "width":379,
              "height":347}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58376dae09a143a2b451348c86fcbf44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":571,
                  "y":147},
                "size":{
                  "width":379,
                  "height":347}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"907d61e7c04c42d18b5b703b002c373c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"c6cbda40d44a4334981f0015c84e66f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":570,
              "y":467},
            "size":{
              "width":139,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a310232b43cc4ae0a388d4e4124e31ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":570,
                  "y":467},
                "size":{
                  "width":139,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Host event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"host_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"e42ad831e3174218abb103d855e370d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":811,
              "y":467},
            "size":{
              "width":139,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ac8ce4124a4405883a747956d35458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":811,
                  "y":467},
                "size":{
                  "width":139,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Rent office in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"rent_office.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"b9761ebe7eb144ebad3c6982d1f70b1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":584},
            "size":{
              "width":319,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"185f383c62f14b10abb5027fc8e7235f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":584},
                "size":{
                  "width":319,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"d658affe449a4870839ae14b46a346b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":316,
              "y":584},
            "size":{
              "width":319,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d57951c03bf54470a0e9c41f552d4a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":316,
                  "y":584},
                "size":{
                  "width":319,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"24cdd37c098f49478c9564495c427a88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":630,
              "y":584},
            "size":{
              "width":319,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d186bdc3150c4c6cb91154d7af2efb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":630,
                  "y":584},
                "size":{
                  "width":319,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"9ee4ccc86878452badef954a1e0ca1fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":871},
            "size":{
              "width":550,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"903dbe5ade864ede80eacfe46008a969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":871},
                "size":{
                  "width":550,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u53.png"}},
{
          "id":"7067588898da4a8caf6ddbcf123e2577",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":728},
            "size":{
              "width":550,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d3ef8773854d2c8e691ed6097c1d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":728},
                "size":{
                  "width":550,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"162c79315eb8470a85545f9b0147df90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1014},
            "size":{
              "width":550,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f011458c78644f4bb030717090e8a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1014},
                "size":{
                  "width":550,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"d86eeaca62c0480ea76f38d75c03d175",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":570,
              "y":758},
            "size":{
              "width":189,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d47dcd5ab6f4998955334f58829552e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":570,
                  "y":758},
                "size":{
                  "width":189,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cafe in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cafe.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u59.png"}},
{
          "id":"1ff7ef4c82bd4b21b24f4d9d966c6644",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":758},
            "size":{
              "width":170,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16adda447424286aff743b0878772a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":758},
                "size":{
                  "width":170,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cafe in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cafe.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3106500af7934da8839c29d975aad908",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":570,
              "y":891},
            "size":{
              "width":189,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff27bf9dcef44f1a6a9f70354b203bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":570,
                  "y":891},
                "size":{
                  "width":189,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open For children in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"for_children.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u59.png"}},
{
          "id":"d175f344a2d24cd5a0cbac825bcfc488",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":891},
            "size":{
              "width":170,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05803184883a4ec58ce46f1f678313f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":891},
                "size":{
                  "width":170,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open For children in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"for_children.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4d05c227e8643709a399c8b0cf7d68e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":570,
              "y":1024},
            "size":{
              "width":189,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f88fe7d03783469f946e868b9d690146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":570,
                  "y":1024},
                "size":{
                  "width":189,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cafe in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cafe.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u59.png"}},
{
          "id":"28d6d719272944059e4ba8684dcdee02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":1024},
            "size":{
              "width":159,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f10779c40be4a299dcfd05a8fb47e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":1024},
                "size":{
                  "width":159,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cafe in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cafe.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca3e6492aec4e15a675d79483969ea5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":758},
            "size":{
              "width":96,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e57f6ff1fbe46f896de9231c57a1ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":758},
                "size":{
                  "width":96,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6db6474aa4a548e89105e5d88181190f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":901},
            "size":{
              "width":85,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c8662ab82143daba925ddcc6227fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":901},
                "size":{
                  "width":85,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdb31a0dc10c42c7bf1954302626e10b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1044},
            "size":{
              "width":96,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3a2f62bc49a445dbefe7a8ce701868a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1044},
                "size":{
                  "width":96,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd50c3cbaf8d46bfae9fb8d8b17f2cce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":772},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00015707777d47dbb455ae45c1e55581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":772},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f766452f56b46e08721763dca6ccd4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":912},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e3fbb6578034d45934f9dbbef4bbe17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":912},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Host event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"host_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8990ae133e4f474cbfa1eb21bcf8fe74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1054},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fcf8f50d199432792e6433202c6d34a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1054},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b30b6172a2d47b18cc7569fc9701821",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":633},
            "size":{
              "width":260,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307ca0b39cc445b39334efe816b8d10a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":633},
                "size":{
                  "width":260,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43c35044024c405584668b2c0488e2f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":10,
              "y":599},
            "size":{
              "width":102,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35ab9a03398e4eac888a25d7567ff5f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":10,
                  "y":599},
                "size":{
                  "width":102,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1885c1896d64ae083d5da745277d5ee",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":633}},
          "adaptiveStyles":{
},
          "masterId":"eeb13c352dab4b18b8d45a968d13e7eb"},
{
          "id":"560b937d384c41c6b7ae6b14c94fb883",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":633},
            "size":{
              "width":260,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9578c44aaaa45c9923fd4ff690812e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":633},
                "size":{
                  "width":260,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b706866c042d464a84866b20ac0c52dc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1325}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"a69247ee64054c11bd576eb65d8654f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":851,
              "y":599},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d95db537c7d4d809f0464d67502be22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":851,
                  "y":599},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9db5e6587f8c426d9e9e90e884cb70d0",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1157},
            "size":{
              "width":960,
              "height":173}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "d323c5882809487ba803b1c84f4064a2":{
      "packageId":"d323c5882809487ba803b1c84f4064a2",
      "type":"Axure:Master",
      "name":"Блок Мероприятия",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"17f063005a0b425792ddd77bd5c4487e",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"d19c1b09c5164469bc2656b123233ab7"}]}},
    "d19c1b09c5164469bc2656b123233ab7":{
      "packageId":"d19c1b09c5164469bc2656b123233ab7",
      "type":"Axure:Master",
      "name":"Блок Мероприятия",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0bee45b49d5c40d1bd841e79bb41c136",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":204},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5b0a7dfdd2e492681dba5e67dfce7da",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":204},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u4.png"}},
{
            "id":"d4af648f66c94a91896ea0e38dcd7239",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"24px",
              "location":{
                "x":9,
                "y":16},
              "size":{
                "width":164,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5727d51b8b1149019ed58c9c37b45d3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"24px",
                  "location":{
                    "x":9,
                    "y":16},
                  "size":{
                    "width":164,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4cba7a65f540447cb1fe4c01ba82cec1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":61},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"849b1d81fb9e40c1a8d66fe4b15a0a77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":61},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u8.png"}},
{
            "id":"7cb9ec97e1804c518bbfaa51d6b4f863",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":91},
              "size":{
                "width":86,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1de72a26c33041809d26e3dc109a729a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":91},
                  "size":{
                    "width":86,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f29c6590040340d7855e56692b5d8166",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":232,
                "y":102},
              "size":{
                "width":300,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2cde6a31ea4744cf988b924e41a9d3af",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":232,
                    "y":102},
                  "size":{
                    "width":300,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9b6492dcd3da4891bee46a139b423479",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":348},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1dd29ddf361745ccae45182a70343c1e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":348},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u8.png"}},
{
            "id":"8751aa2c9eb4478bbc5f6245747f0929",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":215},
              "size":{
                "width":85,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b24b1f4119c4efebdd50c79b8200327",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":215},
                  "size":{
                    "width":85,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872dc8f8158444eeab938aab4e38819b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":233,
                "y":235},
              "size":{
                "width":300,
                "height":103}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e56942cff89542548da9f931c3dbdf99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":233,
                    "y":235},
                  "size":{
                    "width":300,
                    "height":103}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"33291dba0620481dad1b98a2f16a5790",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":378},
              "size":{
                "width":96,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce964a03a5a54c6ab1123b75ecdd80f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":378},
                  "size":{
                    "width":96,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00efdc479ed342ac9e91c93b586e3292",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":233,
                "y":396},
              "size":{
                "width":300,
                "height":48}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a58169c335704a7495da57d0b8f13e55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":233,
                    "y":396},
                  "size":{
                    "width":300,
                    "height":48}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "eeb13c352dab4b18b8d45a968d13e7eb":{
      "packageId":"eeb13c352dab4b18b8d45a968d13e7eb",
      "type":"Axure:Master",
      "name":"Превью новости",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a026e81074424a60bf05ab69d75c82fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":260,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa10f14c7b7a4eab8c6c2109ab445b87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":260,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One news in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u88.png"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png"}}]}}},
  "objectPaths":{
    "20823511ad0e40099e6be788f8242b1b":{
      "scriptId":"u0"},
    "f940fde377cc48d096806d8f24501892":{
      "scriptId":"u1"},
    "ebd6aad4180a4b06b1242b42fa0fa3a6":{
      "scriptId":"u2",
      "17f063005a0b425792ddd77bd5c4487e":{
        "scriptId":"u3",
        "0bee45b49d5c40d1bd841e79bb41c136":{
          "scriptId":"u4"},
        "c5b0a7dfdd2e492681dba5e67dfce7da":{
          "scriptId":"u5"},
        "d4af648f66c94a91896ea0e38dcd7239":{
          "scriptId":"u6"},
        "5727d51b8b1149019ed58c9c37b45d3b":{
          "scriptId":"u7"},
        "4cba7a65f540447cb1fe4c01ba82cec1":{
          "scriptId":"u8"},
        "849b1d81fb9e40c1a8d66fe4b15a0a77":{
          "scriptId":"u9"},
        "7cb9ec97e1804c518bbfaa51d6b4f863":{
          "scriptId":"u10"},
        "1de72a26c33041809d26e3dc109a729a":{
          "scriptId":"u11"},
        "f29c6590040340d7855e56692b5d8166":{
          "scriptId":"u12"},
        "2cde6a31ea4744cf988b924e41a9d3af":{
          "scriptId":"u13"},
        "9b6492dcd3da4891bee46a139b423479":{
          "scriptId":"u14"},
        "1dd29ddf361745ccae45182a70343c1e":{
          "scriptId":"u15"},
        "8751aa2c9eb4478bbc5f6245747f0929":{
          "scriptId":"u16"},
        "9b24b1f4119c4efebdd50c79b8200327":{
          "scriptId":"u17"},
        "872dc8f8158444eeab938aab4e38819b":{
          "scriptId":"u18"},
        "e56942cff89542548da9f931c3dbdf99":{
          "scriptId":"u19"},
        "33291dba0620481dad1b98a2f16a5790":{
          "scriptId":"u20"},
        "ce964a03a5a54c6ab1123b75ecdd80f3":{
          "scriptId":"u21"},
        "00efdc479ed342ac9e91c93b586e3292":{
          "scriptId":"u22"},
        "a58169c335704a7495da57d0b8f13e55":{
          "scriptId":"u23"}}},
    "7597e0502d2a42b7958ac11993fa954f":{
      "scriptId":"u24"},
    "58376dae09a143a2b451348c86fcbf44":{
      "scriptId":"u25"},
    "907d61e7c04c42d18b5b703b002c373c":{
      "scriptId":"u26",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u27"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u28"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u29"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u30"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u31"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u32"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u33"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u34"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u35"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u36"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u37"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u38"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u39"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u40"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u41"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u42"}},
    "c6cbda40d44a4334981f0015c84e66f6":{
      "scriptId":"u43"},
    "a310232b43cc4ae0a388d4e4124e31ca":{
      "scriptId":"u44"},
    "e42ad831e3174218abb103d855e370d8":{
      "scriptId":"u45"},
    "67ac8ce4124a4405883a747956d35458":{
      "scriptId":"u46"},
    "b9761ebe7eb144ebad3c6982d1f70b1e":{
      "scriptId":"u47"},
    "185f383c62f14b10abb5027fc8e7235f":{
      "scriptId":"u48"},
    "d658affe449a4870839ae14b46a346b5":{
      "scriptId":"u49"},
    "d57951c03bf54470a0e9c41f552d4a5b":{
      "scriptId":"u50"},
    "24cdd37c098f49478c9564495c427a88":{
      "scriptId":"u51"},
    "d186bdc3150c4c6cb91154d7af2efb60":{
      "scriptId":"u52"},
    "9ee4ccc86878452badef954a1e0ca1fa":{
      "scriptId":"u53"},
    "903dbe5ade864ede80eacfe46008a969":{
      "scriptId":"u54"},
    "7067588898da4a8caf6ddbcf123e2577":{
      "scriptId":"u55"},
    "53d3ef8773854d2c8e691ed6097c1d65":{
      "scriptId":"u56"},
    "162c79315eb8470a85545f9b0147df90":{
      "scriptId":"u57"},
    "0f011458c78644f4bb030717090e8a90":{
      "scriptId":"u58"},
    "d86eeaca62c0480ea76f38d75c03d175":{
      "scriptId":"u59"},
    "2d47dcd5ab6f4998955334f58829552e":{
      "scriptId":"u60"},
    "1ff7ef4c82bd4b21b24f4d9d966c6644":{
      "scriptId":"u61"},
    "b16adda447424286aff743b0878772a1":{
      "scriptId":"u62"},
    "3106500af7934da8839c29d975aad908":{
      "scriptId":"u63"},
    "5ff27bf9dcef44f1a6a9f70354b203bb":{
      "scriptId":"u64"},
    "d175f344a2d24cd5a0cbac825bcfc488":{
      "scriptId":"u65"},
    "05803184883a4ec58ce46f1f678313f4":{
      "scriptId":"u66"},
    "e4d05c227e8643709a399c8b0cf7d68e":{
      "scriptId":"u67"},
    "f88fe7d03783469f946e868b9d690146":{
      "scriptId":"u68"},
    "28d6d719272944059e4ba8684dcdee02":{
      "scriptId":"u69"},
    "2f10779c40be4a299dcfd05a8fb47e4d":{
      "scriptId":"u70"},
    "8ca3e6492aec4e15a675d79483969ea5":{
      "scriptId":"u71"},
    "0e57f6ff1fbe46f896de9231c57a1ee4":{
      "scriptId":"u72"},
    "6db6474aa4a548e89105e5d88181190f":{
      "scriptId":"u73"},
    "46c8662ab82143daba925ddcc6227fa3":{
      "scriptId":"u74"},
    "cdb31a0dc10c42c7bf1954302626e10b":{
      "scriptId":"u75"},
    "b3a2f62bc49a445dbefe7a8ce701868a":{
      "scriptId":"u76"},
    "bd50c3cbaf8d46bfae9fb8d8b17f2cce":{
      "scriptId":"u77"},
    "00015707777d47dbb455ae45c1e55581":{
      "scriptId":"u78"},
    "2f766452f56b46e08721763dca6ccd4f":{
      "scriptId":"u79"},
    "8e3fbb6578034d45934f9dbbef4bbe17":{
      "scriptId":"u80"},
    "8990ae133e4f474cbfa1eb21bcf8fe74":{
      "scriptId":"u81"},
    "3fcf8f50d199432792e6433202c6d34a":{
      "scriptId":"u82"},
    "2b30b6172a2d47b18cc7569fc9701821":{
      "scriptId":"u83"},
    "307ca0b39cc445b39334efe816b8d10a":{
      "scriptId":"u84"},
    "43c35044024c405584668b2c0488e2f9":{
      "scriptId":"u85"},
    "35ab9a03398e4eac888a25d7567ff5f8":{
      "scriptId":"u86"},
    "e1885c1896d64ae083d5da745277d5ee":{
      "scriptId":"u87",
      "a026e81074424a60bf05ab69d75c82fe":{
        "scriptId":"u88"},
      "fa10f14c7b7a4eab8c6c2109ab445b87":{
        "scriptId":"u89"}},
    "560b937d384c41c6b7ae6b14c94fb883":{
      "scriptId":"u90"},
    "b9578c44aaaa45c9923fd4ff690812e1":{
      "scriptId":"u91"},
    "b706866c042d464a84866b20ac0c52dc":{
      "scriptId":"u92",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u93"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u94"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u95"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u96"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u97"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u98"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u99"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u100"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u101"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u102"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u103"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u104"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u105"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u106"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u107"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u108"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u109"}},
    "a69247ee64054c11bd576eb65d8654f8":{
      "scriptId":"u110"},
    "9d95db537c7d4d809f0464d67502be22":{
      "scriptId":"u111"},
    "9db5e6587f8c426d9e9e90e884cb70d0":{
      "scriptId":"u112"}}});