$axure.loadCurrentPage({
  "url":"events.html",
  "generationDate":new Date(1378338554680.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c854fac592804b0c8c80f74396f52046",
    "type":"Axure:Page",
    "name":"Events",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"20d1b3aa98634eb2bf16ebcbc6558dce",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"6f782762013b4c019091b17cc9a0fc1b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":107}},
          "adaptiveStyles":{
},
          "masterId":"d323c5882809487ba803b1c84f4064a2"},
{
          "id":"a231ef20ac35457da198f6892db208af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":578,
              "y":107},
            "size":{
              "width":102,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35134873cd554c3083e080c8ed264791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":578,
                  "y":107},
                "size":{
                  "width":102,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92e31941242b4fc1bb105b807761bc23",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":562}},
          "adaptiveStyles":{
},
          "masterId":"ef93e196ff7f4dd6859df355dfd519d9"},
{
          "id":"be709efd810f4521a8331b262a9e5395",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":705}},
          "adaptiveStyles":{
},
          "masterId":"ef93e196ff7f4dd6859df355dfd519d9"},
{
          "id":"0953155246c644398f22865209a9a95a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":907}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"5d06b24ddaad49b28353098e8c824e8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":190,
              "y":115},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea6faccb15b47e6aeca69ab82c6aec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":190,
                  "y":115},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1a17a62f0d9462f9619ae559453d23b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":570,
              "y":152},
            "size":{
              "width":390,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f04d2dca7b450c8581ad64b485fa5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":570,
                  "y":152},
                "size":{
                  "width":390,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/events/u75.png"}},
{
          "id":"f5a3435b1f924be6ae13f9d387a6aedf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":295},
            "size":{
              "width":390,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ef8cdafae84f7ca52ee2ada184c3bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":295},
                "size":{
                  "width":390,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/events/u77.png"}},
{
          "id":"e4235f98224f434ab68f306e3b500046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":570,
              "y":439},
            "size":{
              "width":390,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82828d58dc0c46988b438c0a8e7b3c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":570,
                  "y":439},
                "size":{
                  "width":390,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/events/u75.png"}},
{
          "id":"d9470992219e43fbab8e8ff0369becac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":582},
            "size":{
              "width":390,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1611160c2aa41a2ae3bdcc147d614ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":582},
                "size":{
                  "width":390,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/events/u77.png"}},
{
          "id":"66b6407702294568aff0abce8b40529c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":189},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6798fbd2d3c43b3b6c05ae071b73265",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":189},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5d4cd70aa7e436d9626012af980c1ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":333},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5df933207d4d4359ba74725e19ca9d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":333},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec4f811592204c31a8dac7e6280f6f9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":477},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc4f6e3468e4c4895d50053ddac69fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":477},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a08516eea4a743f08027ff0d68a2fee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":621},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfbbc5d5f2f74fdabd5763f73d03b4ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":621},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"501622c540994dafa4477e064d269b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":699,
              "y":114},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d94cc4018114bd595136bdee4cda2b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":699,
                  "y":114},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "d323c5882809487ba803b1c84f4064a2":{
      "packageId":"d323c5882809487ba803b1c84f4064a2",
      "type":"Axure:Master",
      "name":"Блок Мероприятия",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"17f063005a0b425792ddd77bd5c4487e",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"d19c1b09c5164469bc2656b123233ab7"}]}},
    "d19c1b09c5164469bc2656b123233ab7":{
      "packageId":"d19c1b09c5164469bc2656b123233ab7",
      "type":"Axure:Master",
      "name":"Блок Мероприятия",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0bee45b49d5c40d1bd841e79bb41c136",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":204},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5b0a7dfdd2e492681dba5e67dfce7da",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":204},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u4.png"}},
{
            "id":"d4af648f66c94a91896ea0e38dcd7239",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"24px",
              "location":{
                "x":9,
                "y":16},
              "size":{
                "width":164,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5727d51b8b1149019ed58c9c37b45d3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"24px",
                  "location":{
                    "x":9,
                    "y":16},
                  "size":{
                    "width":164,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4cba7a65f540447cb1fe4c01ba82cec1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":61},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"849b1d81fb9e40c1a8d66fe4b15a0a77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":61},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u8.png"}},
{
            "id":"7cb9ec97e1804c518bbfaa51d6b4f863",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":91},
              "size":{
                "width":86,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1de72a26c33041809d26e3dc109a729a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":91},
                  "size":{
                    "width":86,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f29c6590040340d7855e56692b5d8166",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":232,
                "y":102},
              "size":{
                "width":300,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2cde6a31ea4744cf988b924e41a9d3af",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":232,
                    "y":102},
                  "size":{
                    "width":300,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9b6492dcd3da4891bee46a139b423479",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":348},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1dd29ddf361745ccae45182a70343c1e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":348},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u8.png"}},
{
            "id":"8751aa2c9eb4478bbc5f6245747f0929",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":215},
              "size":{
                "width":85,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b24b1f4119c4efebdd50c79b8200327",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":215},
                  "size":{
                    "width":85,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872dc8f8158444eeab938aab4e38819b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":233,
                "y":235},
              "size":{
                "width":300,
                "height":103}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e56942cff89542548da9f931c3dbdf99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":233,
                    "y":235},
                  "size":{
                    "width":300,
                    "height":103}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"33291dba0620481dad1b98a2f16a5790",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":378},
              "size":{
                "width":96,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce964a03a5a54c6ab1123b75ecdd80f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":378},
                  "size":{
                    "width":96,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00efdc479ed342ac9e91c93b586e3292",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":233,
                "y":396},
              "size":{
                "width":300,
                "height":48}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a58169c335704a7495da57d0b8f13e55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":233,
                    "y":396},
                  "size":{
                    "width":300,
                    "height":48}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "ef93e196ff7f4dd6859df355dfd519d9":{
      "packageId":"ef93e196ff7f4dd6859df355dfd519d9",
      "type":"Axure:Master",
      "name":"Блок 1 мероприятие",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3496c90928cd4b509b661e1a6e3e4825",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "size":{
                "width":550,
                "height":145}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f37bc43e15fa476ba39fbcc0d4837bd6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "size":{
                    "width":550,
                    "height":145}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/events/u42.png",
              "normal~":"images/events/u42.png"}},
{
            "id":"b31cfd69295e4e6ba7f2b16a68e5411a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":30},
              "size":{
                "width":96,
                "height":85}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5e53ea4240f479f8f57c9317758fcd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":30},
                  "size":{
                    "width":96,
                    "height":85}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1ce9ae57cb5d4393b5ab01d191f79c17",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":250,
                "y":41},
              "size":{
                "width":300,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"195657029d2f4673ab90f27e5b11ee3d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":250,
                    "y":41},
                  "size":{
                    "width":300,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png"}}]}}},
  "objectPaths":{
    "20d1b3aa98634eb2bf16ebcbc6558dce":{
      "scriptId":"u0",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u1"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u2"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u3"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u4"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u5"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u6"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u7"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u8"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u9"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u10"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u11"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u12"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u13"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u14"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u15"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u16"}},
    "6f782762013b4c019091b17cc9a0fc1b":{
      "scriptId":"u17",
      "17f063005a0b425792ddd77bd5c4487e":{
        "scriptId":"u18",
        "0bee45b49d5c40d1bd841e79bb41c136":{
          "scriptId":"u19"},
        "c5b0a7dfdd2e492681dba5e67dfce7da":{
          "scriptId":"u20"},
        "d4af648f66c94a91896ea0e38dcd7239":{
          "scriptId":"u21"},
        "5727d51b8b1149019ed58c9c37b45d3b":{
          "scriptId":"u22"},
        "4cba7a65f540447cb1fe4c01ba82cec1":{
          "scriptId":"u23"},
        "849b1d81fb9e40c1a8d66fe4b15a0a77":{
          "scriptId":"u24"},
        "7cb9ec97e1804c518bbfaa51d6b4f863":{
          "scriptId":"u25"},
        "1de72a26c33041809d26e3dc109a729a":{
          "scriptId":"u26"},
        "f29c6590040340d7855e56692b5d8166":{
          "scriptId":"u27"},
        "2cde6a31ea4744cf988b924e41a9d3af":{
          "scriptId":"u28"},
        "9b6492dcd3da4891bee46a139b423479":{
          "scriptId":"u29"},
        "1dd29ddf361745ccae45182a70343c1e":{
          "scriptId":"u30"},
        "8751aa2c9eb4478bbc5f6245747f0929":{
          "scriptId":"u31"},
        "9b24b1f4119c4efebdd50c79b8200327":{
          "scriptId":"u32"},
        "872dc8f8158444eeab938aab4e38819b":{
          "scriptId":"u33"},
        "e56942cff89542548da9f931c3dbdf99":{
          "scriptId":"u34"},
        "33291dba0620481dad1b98a2f16a5790":{
          "scriptId":"u35"},
        "ce964a03a5a54c6ab1123b75ecdd80f3":{
          "scriptId":"u36"},
        "00efdc479ed342ac9e91c93b586e3292":{
          "scriptId":"u37"},
        "a58169c335704a7495da57d0b8f13e55":{
          "scriptId":"u38"}}},
    "a231ef20ac35457da198f6892db208af":{
      "scriptId":"u39"},
    "35134873cd554c3083e080c8ed264791":{
      "scriptId":"u40"},
    "92e31941242b4fc1bb105b807761bc23":{
      "scriptId":"u41",
      "3496c90928cd4b509b661e1a6e3e4825":{
        "scriptId":"u42"},
      "f37bc43e15fa476ba39fbcc0d4837bd6":{
        "scriptId":"u43"},
      "b31cfd69295e4e6ba7f2b16a68e5411a":{
        "scriptId":"u44"},
      "d5e53ea4240f479f8f57c9317758fcd7":{
        "scriptId":"u45"},
      "1ce9ae57cb5d4393b5ab01d191f79c17":{
        "scriptId":"u46"},
      "195657029d2f4673ab90f27e5b11ee3d":{
        "scriptId":"u47"}},
    "be709efd810f4521a8331b262a9e5395":{
      "scriptId":"u48",
      "3496c90928cd4b509b661e1a6e3e4825":{
        "scriptId":"u49"},
      "f37bc43e15fa476ba39fbcc0d4837bd6":{
        "scriptId":"u50"},
      "b31cfd69295e4e6ba7f2b16a68e5411a":{
        "scriptId":"u51"},
      "d5e53ea4240f479f8f57c9317758fcd7":{
        "scriptId":"u52"},
      "1ce9ae57cb5d4393b5ab01d191f79c17":{
        "scriptId":"u53"},
      "195657029d2f4673ab90f27e5b11ee3d":{
        "scriptId":"u54"}},
    "0953155246c644398f22865209a9a95a":{
      "scriptId":"u55",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u56"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u57"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u58"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u59"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u60"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u61"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u62"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u63"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u64"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u65"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u66"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u67"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u68"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u69"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u70"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u71"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u72"}},
    "5d06b24ddaad49b28353098e8c824e8c":{
      "scriptId":"u73"},
    "9ea6faccb15b47e6aeca69ab82c6aec5":{
      "scriptId":"u74"},
    "f1a17a62f0d9462f9619ae559453d23b":{
      "scriptId":"u75"},
    "f8f04d2dca7b450c8581ad64b485fa5a":{
      "scriptId":"u76"},
    "f5a3435b1f924be6ae13f9d387a6aedf":{
      "scriptId":"u77"},
    "91ef8cdafae84f7ca52ee2ada184c3bc":{
      "scriptId":"u78"},
    "e4235f98224f434ab68f306e3b500046":{
      "scriptId":"u79"},
    "82828d58dc0c46988b438c0a8e7b3c56":{
      "scriptId":"u80"},
    "d9470992219e43fbab8e8ff0369becac":{
      "scriptId":"u81"},
    "e1611160c2aa41a2ae3bdcc147d614ca":{
      "scriptId":"u82"},
    "66b6407702294568aff0abce8b40529c":{
      "scriptId":"u83"},
    "f6798fbd2d3c43b3b6c05ae071b73265":{
      "scriptId":"u84"},
    "f5d4cd70aa7e436d9626012af980c1ab":{
      "scriptId":"u85"},
    "5df933207d4d4359ba74725e19ca9d99":{
      "scriptId":"u86"},
    "ec4f811592204c31a8dac7e6280f6f9e":{
      "scriptId":"u87"},
    "adc4f6e3468e4c4895d50053ddac69fc":{
      "scriptId":"u88"},
    "a08516eea4a743f08027ff0d68a2fee6":{
      "scriptId":"u89"},
    "dfbbc5d5f2f74fdabd5763f73d03b4ae":{
      "scriptId":"u90"},
    "501622c540994dafa4477e064d269b91":{
      "scriptId":"u91"},
    "6d94cc4018114bd595136bdee4cda2b5":{
      "scriptId":"u92"}}});