$axure.loadCurrentPage({
  "url":"one_tenant.html",
  "generationDate":new Date(1378338555566.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"baa37939afbc4067900e044d6fb0e04c",
    "type":"Axure:Page",
    "name":"One tenant",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"76193626a4fc4b5b93cb5a120cf34fb1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"88ec9d7af32a4966ad68ad48cbf24971",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":9,
              "y":107},
            "size":{
              "width":205,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af6504e2e804e41b49426558f70d76d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":9,
                  "y":107},
                "size":{
                  "width":205,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"537b3dea4201465696cab8df64d248dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":135},
            "size":{
              "width":590,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/one_tenant/u19_line.png"}},
{
          "id":"8cb5d00add834f989f97dbd11b02b05b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":11,
              "y":160},
            "size":{
              "width":150,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac50824e5ea4ecea6e8649da5fb7c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":11,
                  "y":160},
                "size":{
                  "width":150,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/one_tenant/u20.png"}},
{
          "id":"3283384a3f5046c68cad40c484e1cea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":231},
            "size":{
              "width":580,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae33130a5cb4d57b9b204ba24bb99e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":231},
                "size":{
                  "width":580,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b6a5b9d23534f0e84c6330c49a81964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":267},
            "size":{
              "width":590,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b2d120ea4274019a3ef2b92c67746e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":267},
                "size":{
                  "width":590,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"702bcc8934754cc0bc6481cbc214e207",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":580,
              "height":325}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991103e578944136b9c2ea3aefb6a392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":580,
                  "height":325}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/one_tenant/u26.png"}},
{
          "id":"5d3bd1a376554d36b5715da05f259920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":631,
              "y":258},
            "size":{
              "width":318,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a8aaac706849e7b2b947e175542193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":631,
                  "y":258},
                "size":{
                  "width":318,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ac009cf2b1740cebda485e570520d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":630,
              "y":160},
            "size":{
              "width":120,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0a61c00dea4f65abb9f7ca6efd8f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":630,
                  "y":160},
                "size":{
                  "width":120,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/host_event/u58.png"}},
{
          "id":"b523344bd5b140278c7c6975be0be846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":631,
              "y":435},
            "size":{
              "width":318,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71bcd96c16334528a573f1cd1470ec68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":631,
                  "y":435},
                "size":{
                  "width":318,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"303ebfd4fafe4a52a6e7227375c78cd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":630,
              "y":335},
            "size":{
              "width":120,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09d812da43b43fa80a88387398c3a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":630,
                  "y":335},
                "size":{
                  "width":120,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/host_event/u58.png"}},
{
          "id":"3ba5e96f20f7448bb4f98b10f5fadaec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":178,
              "y":180},
            "size":{
              "width":404,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20414ec8af6347c1a910a36a40fead56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":178,
                  "y":180},
                "size":{
                  "width":404,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"945af37504ac48198e07ca9297efdbe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":774},
            "size":{
              "width":590,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06839f72a92c4b20ac2a5a9a77d08977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":774},
                "size":{
                  "width":590,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bccddfddbd244cad9efbdebc4af14ecf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":895}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"}]}},
  "masters":{
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png"}}]}}},
  "objectPaths":{
    "76193626a4fc4b5b93cb5a120cf34fb1":{
      "scriptId":"u0",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u1"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u2"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u3"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u4"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u5"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u6"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u7"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u8"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u9"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u10"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u11"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u12"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u13"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u14"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u15"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u16"}},
    "88ec9d7af32a4966ad68ad48cbf24971":{
      "scriptId":"u17"},
    "3af6504e2e804e41b49426558f70d76d":{
      "scriptId":"u18"},
    "537b3dea4201465696cab8df64d248dd":{
      "scriptId":"u19"},
    "8cb5d00add834f989f97dbd11b02b05b":{
      "scriptId":"u20"},
    "2ac50824e5ea4ecea6e8649da5fb7c24":{
      "scriptId":"u21"},
    "3283384a3f5046c68cad40c484e1cea4":{
      "scriptId":"u22"},
    "5ae33130a5cb4d57b9b204ba24bb99e6":{
      "scriptId":"u23"},
    "7b6a5b9d23534f0e84c6330c49a81964":{
      "scriptId":"u24"},
    "6b2d120ea4274019a3ef2b92c67746e0":{
      "scriptId":"u25"},
    "702bcc8934754cc0bc6481cbc214e207":{
      "scriptId":"u26"},
    "991103e578944136b9c2ea3aefb6a392":{
      "scriptId":"u27"},
    "5d3bd1a376554d36b5715da05f259920":{
      "scriptId":"u28"},
    "e1a8aaac706849e7b2b947e175542193":{
      "scriptId":"u29"},
    "4ac009cf2b1740cebda485e570520d21":{
      "scriptId":"u30"},
    "0f0a61c00dea4f65abb9f7ca6efd8f8e":{
      "scriptId":"u31"},
    "b523344bd5b140278c7c6975be0be846":{
      "scriptId":"u32"},
    "71bcd96c16334528a573f1cd1470ec68":{
      "scriptId":"u33"},
    "303ebfd4fafe4a52a6e7227375c78cd2":{
      "scriptId":"u34"},
    "b09d812da43b43fa80a88387398c3a51":{
      "scriptId":"u35"},
    "3ba5e96f20f7448bb4f98b10f5fadaec":{
      "scriptId":"u36"},
    "20414ec8af6347c1a910a36a40fead56":{
      "scriptId":"u37"},
    "945af37504ac48198e07ca9297efdbe2":{
      "scriptId":"u38"},
    "06839f72a92c4b20ac2a5a9a77d08977":{
      "scriptId":"u39"},
    "bccddfddbd244cad9efbdebc4af14ecf":{
      "scriptId":"u40",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u41"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u42"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u43"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u44"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u45"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u46"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u47"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u48"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u49"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u50"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u51"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u52"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u53"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u54"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u55"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u56"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u57"}}}});