$axure.loadCurrentPage({
  "url":"soyze_service.html",
  "generationDate":new Date(1382378684707.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"64ef6096000040fcab23c1a74c83a806",
    "type":"Axure:Page",
    "name":"Soyze_Service",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0685f38239664e1f8bd7fd57cb205e5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":330,
              "y":139},
            "size":{
              "width":80,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98e4a6b8306049c2b60ba2992fd61ec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":330,
                  "y":139},
                "size":{
                  "width":80,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/information/u0.png"}},
{
          "id":"b1e21cbcae384a37b49b6fac2f970309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FF2F2F2},
            "location":{
              "x":0,
              "y":191},
            "size":{
              "width":1410,
              "height":259},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"559d8c8e6f6b4d7792f7a6eb58af0088",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FF2F2F2},
                "location":{
                  "x":0,
                  "y":191},
                "size":{
                  "width":1410,
                  "height":259},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/soyze_service/u2.png"}},
{
          "id":"11df43f9354a4020b350d402279da920",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":28}},
          "adaptiveStyles":{
},
          "masterId":"4003f31f2bf74a6e960c609db1aebe89"},
{
          "id":"8f7ec42d065946f2b3582d4a34d0f347",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":203,
              "y":285},
            "size":{
              "width":1040,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c536b444d41b4527b0d7e86a846a7423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":203,
                  "y":285},
                "size":{
                  "width":1040,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1919291399d4c2b8cfbc5829055562b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":203,
              "y":506},
            "size":{
              "width":1027,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6c165b5efe24beea99cc541611faccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":203,
                  "y":506},
                "size":{
                  "width":1027,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55f1b0eca8a946d79fe54ecfaca8144a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":630,
              "y":650},
            "size":{
              "width":260,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4ce57bec9d4d698b186ea7d6e543d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":630,
                  "y":650},
                "size":{
                  "width":260,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d13ba4b9777340a8af6466abef7ad46e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "lineSpacing":"25px",
            "location":{
              "x":761,
              "y":860},
            "size":{
              "width":528,
              "height":292}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d50da525ad445949ceef19f50ff5537",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "lineSpacing":"25px",
                "location":{
                  "x":761,
                  "y":860},
                "size":{
                  "width":528,
                  "height":292}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a3daf6d19cd4304b5580c704b4edb4b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":703},
            "size":{
              "width":1186,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/information/u45_line.png"}},
{
          "id":"bcd4dd809e4f4abfbb5c261c9255104f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1858}},
          "adaptiveStyles":{
},
          "masterId":"922385ae9a2e4795bce54b3d94957db1"},
{
          "id":"d9dde1174da84b42a565a97eb1a552d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":99,
              "y":1702},
            "size":{
              "width":1187,
              "height":98},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78ef5fbc0d9241daaa5d36d50d739f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":99,
                  "y":1702},
                "size":{
                  "width":1187,
                  "height":98},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/information/u56.png"}},
{
          "id":"3a3d905a44164d90b9c942ad0ad265dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":554,
              "y":1734},
            "size":{
              "width":281,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e035062cd6f54fa7b9a29e24826c2cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":554,
                  "y":1734},
                "size":{
                  "width":281,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a931937cec8f4796b0a94a2aebf20987",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":139}},
          "adaptiveStyles":{
},
          "masterId":"1c560cbc4292451fae0f4c10b7b76c51"},
{
          "id":"e78d03240c754666b4fde8d01344c01a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "lineSpacing":"20px",
            "location":{
              "x":761,
              "y":1132},
            "size":{
              "width":251,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c1ed7e0c6e480eaf38420cfc46d6e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "lineSpacing":"20px",
                "location":{
                  "x":761,
                  "y":1132},
                "size":{
                  "width":251,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa107d5dbc0841019c590295b901bd59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "lineSpacing":"25px",
            "location":{
              "x":99,
              "y":860},
            "size":{
              "width":528,
              "height":292}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15178ac8ea0f4e6aa4bf3b31b885b646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "lineSpacing":"25px",
                "location":{
                  "x":99,
                  "y":860},
                "size":{
                  "width":528,
                  "height":292}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"695c789990e24cd89f9148743d081184",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "lineSpacing":"20px",
            "location":{
              "x":99,
              "y":1132},
            "size":{
              "width":251,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c637bda72f4743dd8e6dbea3a61ed3fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "lineSpacing":"20px",
                "location":{
                  "x":99,
                  "y":1132},
                "size":{
                  "width":251,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69fb0f8e238748a1a3f21d4932e2d675",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "lineSpacing":"25px",
            "location":{
              "x":99,
              "y":1298},
            "size":{
              "width":528,
              "height":292}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cbb49dc608e47eca7cc181688e51993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "lineSpacing":"25px",
                "location":{
                  "x":99,
                  "y":1298},
                "size":{
                  "width":528,
                  "height":292}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9c361c052bf4379a77fa675278b84d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "lineSpacing":"20px",
            "location":{
              "x":99,
              "y":1570},
            "size":{
              "width":251,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee946751fbd41c591096b18731ef459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "lineSpacing":"20px",
                "location":{
                  "x":99,
                  "y":1570},
                "size":{
                  "width":251,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d34d1fb0e554803a27150312b12baeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "lineSpacing":"25px",
            "location":{
              "x":761,
              "y":1297},
            "size":{
              "width":528,
              "height":292}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba50a8b02a9d416b87257aae0c4094ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "lineSpacing":"25px",
                "location":{
                  "x":761,
                  "y":1297},
                "size":{
                  "width":528,
                  "height":292}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d69f04d0146410c990b51c777bd014e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "lineSpacing":"20px",
            "location":{
              "x":761,
              "y":1569},
            "size":{
              "width":251,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57df2554a3d3498fa933c40d5c6029ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "lineSpacing":"20px",
                "location":{
                  "x":761,
                  "y":1569},
                "size":{
                  "width":251,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d31bb72af3f940ca9bcd20a9677e529f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":99,
              "y":1190},
            "size":{
              "width":90,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e81d57cb7b184b7db9d6c9555dd950d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":99,
                  "y":1190},
                "size":{
                  "width":90,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/soyze_service/u76.png"}},
{
          "id":"1c785bc68a1e4503950b0784b09b8eca",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":761,
              "y":1190},
            "size":{
              "width":90,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3df344ba28d4b889d894f6f200cefb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":761,
                  "y":1190},
                "size":{
                  "width":90,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/soyze_service/u76.png"}},
{
          "id":"8b77bc3982614e548c8c09ecefee7f0e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":99,
              "y":750},
            "size":{
              "width":90,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ffc2a1db14c4742805b76d6d359db2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":99,
                  "y":750},
                "size":{
                  "width":90,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/soyze_service/u76.png"}},
{
          "id":"07ea707a18d34448b201d744a5445cac",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":761,
              "y":750},
            "size":{
              "width":90,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af326a4a641442aa813fa1dc2d54d931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":761,
                  "y":750},
                "size":{
                  "width":90,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/soyze_service/u76.png"}}]}},
  "masters":{
    "4003f31f2bf74a6e960c609db1aebe89":{
      "packageId":"4003f31f2bf74a6e960c609db1aebe89",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1dbc9764fcbc44e4ad363c2678f1b069",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":849,
                "y":26},
              "size":{
                "width":140,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7abf3b60f2994d22a96b415824ddeb6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":849,
                    "y":26},
                  "size":{
                    "width":140,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u12.png"}},
{
            "id":"25fd79716c9b4affa2bee0a5634583e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":179,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e308b5ba81d4c67aa1834bc5d8e1ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":179,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home_page in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home_page.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"46eb76913c0441ccb9e141066e3539b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":229,
                "y":30},
              "size":{
                "width":120,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8fdd90b2d764b56a50c6b57d0f70899",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":229,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b73211a607964d1e9c4b9b9ca1305b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":386,
                "y":30},
              "size":{
                "width":84,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e7927d5c6e84307adc4e5901413e9fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":386,
                    "y":30},
                  "size":{
                    "width":84,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4799bc506564ee0a2570f1d9758f91a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":611,
                "y":30},
              "size":{
                "width":90,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81434af3de0d4e4dab99e62cf20575b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":611,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Projects in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"projects.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbac75afd9474dbaae2adc57fec2dc75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":728,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17723d194de34772936bdf9bbc9cc1a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":728,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"859e819d30d0424b93da19cf9dfc811f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":875,
                "y":29},
              "size":{
                "width":104,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da35e29e2e9045578f9571b1c098f23e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":875,
                    "y":29},
                  "size":{
                    "width":104,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Join in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"join.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"398bd0a3809546b19482b584abcb2d98",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "lineSpacing":"18px",
              "location":{
                "x":1130,
                "y":37},
              "size":{
                "width":59,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e862163b6c1649b9aa4a331c26cca7cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1130,
                    "y":37},
                  "size":{
                    "width":59,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Subscription in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"subscription.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"efd9cc22b1634b98a88cce427449cc61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "lineSpacing":"18px",
              "location":{
                "x":1013,
                "y":38},
              "size":{
                "width":117,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bbf5a4d8e2c4525ae4cbcef65fbff5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1013,
                    "y":38},
                  "size":{
                    "width":117,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872978ca3bf84ab0abce826289c2c1ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":506,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44957ebe00864e8ab23d78c543b3177e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":506,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "922385ae9a2e4795bce54b3d94957db1":{
      "packageId":"922385ae9a2e4795bce54b3d94957db1",
      "type":"Axure:Master",
      "name":"end",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c73453fa386d40dead74146e04ce954f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7FF2F2F2},
              "size":{
                "width":1410,
                "height":230},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8878246103114da49b829355f0c5bdae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7FF2F2F2},
                  "size":{
                    "width":1410,
                    "height":230},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u3.png"}},
{
            "id":"35b1dc1504434f0293e24769738c8e08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":100,
                "y":111},
              "size":{
                "width":519,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f1d119d1ede47d3a712d4b080bbeca8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":111},
                  "size":{
                    "width":519,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fa8ef993a6413681691a78c384fde9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF949494,
                "opacity":1},
              "location":{
                "x":100,
                "y":40},
              "size":{
                "width":1250,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"feb07e2dcb3344d1b08520803a2d24f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF949494,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":40},
                  "size":{
                    "width":1250,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"626bda77e02f4557abebf86faae7ebc1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":1085,
                "y":111},
              "size":{
                "width":229,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ac1e527f59d4a1fb706c277ab155d49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":111},
                  "size":{
                    "width":229,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c560cbc4292451fae0f4c10b7b76c51":{
      "packageId":"1c560cbc4292451fae0f4c10b7b76c51",
      "type":"Axure:Master",
      "name":"Menu2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a4f123e0da45458f8e35fb48faba17b1",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":88,
                "y":69},
              "size":{
                "width":902,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4323b2b3dbc14691ba7216695e5743ff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":88,
                    "y":69},
                  "size":{
                    "width":902,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/information/u61.png"}},
{
            "id":"35225ad5f40c42d0bef320eea6b062ad",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":100,
                "y":71},
              "size":{
                "width":80,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"beadbae8d3db479780cfd1f788332f94",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":100,
                    "y":71},
                  "size":{
                    "width":80,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ae9973c7124c48db8602654217310862",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":421,
                "y":70},
              "size":{
                "width":215,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0816965cb2498d914bd1e5a0f4e8aa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":421,
                    "y":70},
                  "size":{
                    "width":215,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Sections in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"sections.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e877c7534a5c4e3f9be6321d9a22d45d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":683,
                "y":70},
              "size":{
                "width":101,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"63d62f61204c41b7bddde3f3d925a12a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":683,
                    "y":70},
                  "size":{
                    "width":101,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Partners in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"partners.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"560656a05b6349818892f9b1ce778f3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":814,
                "y":70},
              "size":{
                "width":102,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4d781244a314498f9245001b6cff2432",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":814,
                    "y":70},
                  "size":{
                    "width":102,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Documents in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"documents.html",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fb31efab3f774d5fadd72b8053500697",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"400",
              "location":{
                "x":214,
                "y":74},
              "size":{
                "width":71,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ddece461d5d74785aea150665a4ccad8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "location":{
                    "x":214,
                    "y":74},
                  "size":{
                    "width":71,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open History in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"history.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2552a787d0d549a9a07227e8a96cfe7d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"400",
              "location":{
                "x":326,
                "y":74},
              "size":{
                "width":57,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b7f8b846c0c4713a4a37db3fc581951",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "location":{
                    "x":326,
                    "y":74},
                  "size":{
                    "width":57,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "0685f38239664e1f8bd7fd57cb205e5f":{
      "scriptId":"u0"},
    "98e4a6b8306049c2b60ba2992fd61ec4":{
      "scriptId":"u1"},
    "b1e21cbcae384a37b49b6fac2f970309":{
      "scriptId":"u2"},
    "559d8c8e6f6b4d7792f7a6eb58af0088":{
      "scriptId":"u3"},
    "11df43f9354a4020b350d402279da920":{
      "scriptId":"u4",
      "1dbc9764fcbc44e4ad363c2678f1b069":{
        "scriptId":"u5"},
      "7abf3b60f2994d22a96b415824ddeb6a":{
        "scriptId":"u6"},
      "25fd79716c9b4affa2bee0a5634583e3":{
        "scriptId":"u7"},
      "8e308b5ba81d4c67aa1834bc5d8e1ab2":{
        "scriptId":"u8"},
      "46eb76913c0441ccb9e141066e3539b2":{
        "scriptId":"u9"},
      "a8fdd90b2d764b56a50c6b57d0f70899":{
        "scriptId":"u10"},
      "b73211a607964d1e9c4b9b9ca1305b78":{
        "scriptId":"u11"},
      "4e7927d5c6e84307adc4e5901413e9fe":{
        "scriptId":"u12"},
      "e4799bc506564ee0a2570f1d9758f91a":{
        "scriptId":"u13"},
      "81434af3de0d4e4dab99e62cf20575b8":{
        "scriptId":"u14"},
      "dbac75afd9474dbaae2adc57fec2dc75":{
        "scriptId":"u15"},
      "17723d194de34772936bdf9bbc9cc1a9":{
        "scriptId":"u16"},
      "859e819d30d0424b93da19cf9dfc811f":{
        "scriptId":"u17"},
      "da35e29e2e9045578f9571b1c098f23e":{
        "scriptId":"u18"},
      "398bd0a3809546b19482b584abcb2d98":{
        "scriptId":"u19"},
      "e862163b6c1649b9aa4a331c26cca7cb":{
        "scriptId":"u20"},
      "efd9cc22b1634b98a88cce427449cc61":{
        "scriptId":"u21"},
      "9bbf5a4d8e2c4525ae4cbcef65fbff5e":{
        "scriptId":"u22"},
      "872978ca3bf84ab0abce826289c2c1ea":{
        "scriptId":"u23"},
      "44957ebe00864e8ab23d78c543b3177e":{
        "scriptId":"u24"}},
    "8f7ec42d065946f2b3582d4a34d0f347":{
      "scriptId":"u25"},
    "c536b444d41b4527b0d7e86a846a7423":{
      "scriptId":"u26"},
    "c1919291399d4c2b8cfbc5829055562b":{
      "scriptId":"u27"},
    "c6c165b5efe24beea99cc541611faccf":{
      "scriptId":"u28"},
    "55f1b0eca8a946d79fe54ecfaca8144a":{
      "scriptId":"u29"},
    "8d4ce57bec9d4d698b186ea7d6e543d2":{
      "scriptId":"u30"},
    "d13ba4b9777340a8af6466abef7ad46e":{
      "scriptId":"u31"},
    "8d50da525ad445949ceef19f50ff5537":{
      "scriptId":"u32"},
    "5a3daf6d19cd4304b5580c704b4edb4b":{
      "scriptId":"u33"},
    "bcd4dd809e4f4abfbb5c261c9255104f":{
      "scriptId":"u34",
      "c73453fa386d40dead74146e04ce954f":{
        "scriptId":"u35"},
      "8878246103114da49b829355f0c5bdae":{
        "scriptId":"u36"},
      "35b1dc1504434f0293e24769738c8e08":{
        "scriptId":"u37"},
      "1f1d119d1ede47d3a712d4b080bbeca8":{
        "scriptId":"u38"},
      "90fa8ef993a6413681691a78c384fde9":{
        "scriptId":"u39"},
      "feb07e2dcb3344d1b08520803a2d24f3":{
        "scriptId":"u40"},
      "626bda77e02f4557abebf86faae7ebc1":{
        "scriptId":"u41"},
      "9ac1e527f59d4a1fb706c277ab155d49":{
        "scriptId":"u42"}},
    "d9dde1174da84b42a565a97eb1a552d8":{
      "scriptId":"u43"},
    "78ef5fbc0d9241daaa5d36d50d739f6d":{
      "scriptId":"u44"},
    "3a3d905a44164d90b9c942ad0ad265dc":{
      "scriptId":"u45"},
    "e035062cd6f54fa7b9a29e24826c2cc5":{
      "scriptId":"u46"},
    "a931937cec8f4796b0a94a2aebf20987":{
      "scriptId":"u47",
      "a4f123e0da45458f8e35fb48faba17b1":{
        "scriptId":"u48"},
      "4323b2b3dbc14691ba7216695e5743ff":{
        "scriptId":"u49"},
      "35225ad5f40c42d0bef320eea6b062ad":{
        "scriptId":"u50"},
      "beadbae8d3db479780cfd1f788332f94":{
        "scriptId":"u51"},
      "ae9973c7124c48db8602654217310862":{
        "scriptId":"u52"},
      "6b0816965cb2498d914bd1e5a0f4e8aa":{
        "scriptId":"u53"},
      "e877c7534a5c4e3f9be6321d9a22d45d":{
        "scriptId":"u54"},
      "63d62f61204c41b7bddde3f3d925a12a":{
        "scriptId":"u55"},
      "560656a05b6349818892f9b1ce778f3f":{
        "scriptId":"u56"},
      "4d781244a314498f9245001b6cff2432":{
        "scriptId":"u57"},
      "fb31efab3f774d5fadd72b8053500697":{
        "scriptId":"u58"},
      "ddece461d5d74785aea150665a4ccad8":{
        "scriptId":"u59"},
      "2552a787d0d549a9a07227e8a96cfe7d":{
        "scriptId":"u60"},
      "9b7f8b846c0c4713a4a37db3fc581951":{
        "scriptId":"u61"}},
    "e78d03240c754666b4fde8d01344c01a":{
      "scriptId":"u62"},
    "d3c1ed7e0c6e480eaf38420cfc46d6e5":{
      "scriptId":"u63"},
    "fa107d5dbc0841019c590295b901bd59":{
      "scriptId":"u64"},
    "15178ac8ea0f4e6aa4bf3b31b885b646":{
      "scriptId":"u65"},
    "695c789990e24cd89f9148743d081184":{
      "scriptId":"u66"},
    "c637bda72f4743dd8e6dbea3a61ed3fd":{
      "scriptId":"u67"},
    "69fb0f8e238748a1a3f21d4932e2d675":{
      "scriptId":"u68"},
    "6cbb49dc608e47eca7cc181688e51993":{
      "scriptId":"u69"},
    "f9c361c052bf4379a77fa675278b84d3":{
      "scriptId":"u70"},
    "7ee946751fbd41c591096b18731ef459":{
      "scriptId":"u71"},
    "4d34d1fb0e554803a27150312b12baeb":{
      "scriptId":"u72"},
    "ba50a8b02a9d416b87257aae0c4094ca":{
      "scriptId":"u73"},
    "9d69f04d0146410c990b51c777bd014e":{
      "scriptId":"u74"},
    "57df2554a3d3498fa933c40d5c6029ba":{
      "scriptId":"u75"},
    "d31bb72af3f940ca9bcd20a9677e529f":{
      "scriptId":"u76"},
    "e81d57cb7b184b7db9d6c9555dd950d3":{
      "scriptId":"u77"},
    "1c785bc68a1e4503950b0784b09b8eca":{
      "scriptId":"u78"},
    "f3df344ba28d4b889d894f6f200cefb5":{
      "scriptId":"u79"},
    "8b77bc3982614e548c8c09ecefee7f0e":{
      "scriptId":"u80"},
    "4ffc2a1db14c4742805b76d6d359db2b":{
      "scriptId":"u81"},
    "07ea707a18d34448b201d744a5445cac":{
      "scriptId":"u82"},
    "af326a4a641442aa813fa1dc2d54d931":{
      "scriptId":"u83"}}});