$axure.loadCurrentPage({
  "url":"document_page.html",
  "generationDate":new Date(1382378686921.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a73b8ddc9c9d4a46bf58e2fba8d6db36",
    "type":"Axure:Page",
    "name":"Document_page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"15dbf4f618f6401cab811f32cd63b8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":101,
              "y":320},
            "size":{
              "width":173,
              "height":222},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"035d86bfd2374b6b82a3acafc6645997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":101,
                  "y":320},
                "size":{
                  "width":173,
                  "height":222},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/documents/u2.png"}},
{
          "id":"5620bfd5448343ceadffb51e33e88d4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":103,
              "y":564},
            "size":{
              "width":170,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c001ea800e94daba4ac2c7600eaad2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":103,
                  "y":564},
                "size":{
                  "width":170,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88113cbf68494cb3a7775334085dab28",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":141}},
          "adaptiveStyles":{
},
          "masterId":"1c560cbc4292451fae0f4c10b7b76c51"},
{
          "id":"e0efebdec5804e72bc88d9454040e617",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":100,
              "y":221},
            "size":{
              "width":420,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea40f4253adb428da8dd4d6ccf3d33c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":100,
                  "y":221},
                "size":{
                  "width":420,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6293492003f446519c725ef5ca5f9aa4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":28}},
          "adaptiveStyles":{
},
          "masterId":"4003f31f2bf74a6e960c609db1aebe89"},
{
          "id":"a4e869781bf740e4bd79ef38a6a5bd07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":1180,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/partners/u85_line.png"}},
{
          "id":"f2182428faaa4fd08a40733c37446330",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":100,
              "y":596},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf551dab1da4a65adc651f4958368f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":100,
                  "y":596},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9007d45dc3c04691afa68fe8e1977344",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":321,
              "y":320},
            "size":{
              "width":173,
              "height":222},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd7d108ecec43f2be05a501979db0f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":321,
                  "y":320},
                "size":{
                  "width":173,
                  "height":222},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/documents/u2.png"}},
{
          "id":"d6dd99d9a17f42bd844d97fc6f375bb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":323,
              "y":564},
            "size":{
              "width":170,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b12a4d06bbe47c098e791b7088f4a6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":323,
                  "y":564},
                "size":{
                  "width":170,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ade9b6fed4a646e2a3f9188e05d6bad9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":540,
              "y":320},
            "size":{
              "width":173,
              "height":222},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ef6a4fc0106407ca1e4872baabb7d2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":540,
                  "y":320},
                "size":{
                  "width":173,
                  "height":222},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/documents/u2.png"}},
{
          "id":"41f98fbf63da44a590311ee9622bb95c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":542,
              "y":564},
            "size":{
              "width":170,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5acbc9f3317e4818813f1aa858d4b562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":542,
                  "y":564},
                "size":{
                  "width":170,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59213bbfa8064d5eb98c4ac99bda3490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":760,
              "y":320},
            "size":{
              "width":173,
              "height":222},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9af237a4ab3741d380558ab002115af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":760,
                  "y":320},
                "size":{
                  "width":173,
                  "height":222},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/documents/u2.png"}},
{
          "id":"7a14db71e59747efa3e869e83bb0650e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":762,
              "y":564},
            "size":{
              "width":170,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d4a7bab209147249b28e68b63dd3ede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":762,
                  "y":564},
                "size":{
                  "width":170,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbfba0a46f984284845d1f531b27ec6e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1240}},
          "adaptiveStyles":{
},
          "masterId":"922385ae9a2e4795bce54b3d94957db1"},
{
          "id":"6c180861d641493c875f517b21624406",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":321,
              "y":596},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a85b0a45474c3291230926ed5121de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":321,
                  "y":596},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e65bc8c14d44779834b7913e0ee2e33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":542,
              "y":596},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c702f7140b5249cf919d1acc5826bc66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":542,
                  "y":596},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76d54269c73245bfaee946cbdc252bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":763,
              "y":596},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"977b9dd52fb44dcbb06d26555c3d6545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":763,
                  "y":596},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "1c560cbc4292451fae0f4c10b7b76c51":{
      "packageId":"1c560cbc4292451fae0f4c10b7b76c51",
      "type":"Axure:Master",
      "name":"Menu2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a4f123e0da45458f8e35fb48faba17b1",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":88,
                "y":69},
              "size":{
                "width":902,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4323b2b3dbc14691ba7216695e5743ff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":88,
                    "y":69},
                  "size":{
                    "width":902,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/information/u61.png"}},
{
            "id":"35225ad5f40c42d0bef320eea6b062ad",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":100,
                "y":71},
              "size":{
                "width":80,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"beadbae8d3db479780cfd1f788332f94",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":100,
                    "y":71},
                  "size":{
                    "width":80,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ae9973c7124c48db8602654217310862",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":421,
                "y":70},
              "size":{
                "width":215,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0816965cb2498d914bd1e5a0f4e8aa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":421,
                    "y":70},
                  "size":{
                    "width":215,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Sections in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"sections.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e877c7534a5c4e3f9be6321d9a22d45d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":683,
                "y":70},
              "size":{
                "width":101,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"63d62f61204c41b7bddde3f3d925a12a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":683,
                    "y":70},
                  "size":{
                    "width":101,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Partners in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"partners.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"560656a05b6349818892f9b1ce778f3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "lineSpacing":"28px",
              "location":{
                "x":814,
                "y":70},
              "size":{
                "width":102,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4d781244a314498f9245001b6cff2432",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "lineSpacing":"28px",
                  "location":{
                    "x":814,
                    "y":70},
                  "size":{
                    "width":102,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Documents in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"documents.html",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fb31efab3f774d5fadd72b8053500697",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"400",
              "location":{
                "x":214,
                "y":74},
              "size":{
                "width":71,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ddece461d5d74785aea150665a4ccad8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "location":{
                    "x":214,
                    "y":74},
                  "size":{
                    "width":71,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open History in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"history.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2552a787d0d549a9a07227e8a96cfe7d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"400",
              "location":{
                "x":326,
                "y":74},
              "size":{
                "width":57,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b7f8b846c0c4713a4a37db3fc581951",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "location":{
                    "x":326,
                    "y":74},
                  "size":{
                    "width":57,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "4003f31f2bf74a6e960c609db1aebe89":{
      "packageId":"4003f31f2bf74a6e960c609db1aebe89",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1dbc9764fcbc44e4ad363c2678f1b069",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":849,
                "y":26},
              "size":{
                "width":140,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7abf3b60f2994d22a96b415824ddeb6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":849,
                    "y":26},
                  "size":{
                    "width":140,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u12.png"}},
{
            "id":"25fd79716c9b4affa2bee0a5634583e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":179,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e308b5ba81d4c67aa1834bc5d8e1ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":179,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home_page in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home_page.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"46eb76913c0441ccb9e141066e3539b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":229,
                "y":30},
              "size":{
                "width":120,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8fdd90b2d764b56a50c6b57d0f70899",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":229,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b73211a607964d1e9c4b9b9ca1305b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":386,
                "y":30},
              "size":{
                "width":84,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e7927d5c6e84307adc4e5901413e9fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":386,
                    "y":30},
                  "size":{
                    "width":84,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4799bc506564ee0a2570f1d9758f91a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":611,
                "y":30},
              "size":{
                "width":90,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81434af3de0d4e4dab99e62cf20575b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":611,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Projects in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"projects.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbac75afd9474dbaae2adc57fec2dc75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":728,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17723d194de34772936bdf9bbc9cc1a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":728,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"859e819d30d0424b93da19cf9dfc811f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":875,
                "y":29},
              "size":{
                "width":104,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da35e29e2e9045578f9571b1c098f23e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":875,
                    "y":29},
                  "size":{
                    "width":104,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Join in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"join.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"398bd0a3809546b19482b584abcb2d98",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "lineSpacing":"18px",
              "location":{
                "x":1130,
                "y":37},
              "size":{
                "width":59,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e862163b6c1649b9aa4a331c26cca7cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1130,
                    "y":37},
                  "size":{
                    "width":59,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Subscription in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"subscription.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"efd9cc22b1634b98a88cce427449cc61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "lineSpacing":"18px",
              "location":{
                "x":1013,
                "y":38},
              "size":{
                "width":117,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bbf5a4d8e2c4525ae4cbcef65fbff5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1013,
                    "y":38},
                  "size":{
                    "width":117,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872978ca3bf84ab0abce826289c2c1ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":506,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44957ebe00864e8ab23d78c543b3177e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":506,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "922385ae9a2e4795bce54b3d94957db1":{
      "packageId":"922385ae9a2e4795bce54b3d94957db1",
      "type":"Axure:Master",
      "name":"end",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c73453fa386d40dead74146e04ce954f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7FF2F2F2},
              "size":{
                "width":1410,
                "height":230},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8878246103114da49b829355f0c5bdae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7FF2F2F2},
                  "size":{
                    "width":1410,
                    "height":230},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u3.png"}},
{
            "id":"35b1dc1504434f0293e24769738c8e08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":100,
                "y":111},
              "size":{
                "width":519,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f1d119d1ede47d3a712d4b080bbeca8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":111},
                  "size":{
                    "width":519,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fa8ef993a6413681691a78c384fde9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF949494,
                "opacity":1},
              "location":{
                "x":100,
                "y":40},
              "size":{
                "width":1250,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"feb07e2dcb3344d1b08520803a2d24f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF949494,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":40},
                  "size":{
                    "width":1250,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"626bda77e02f4557abebf86faae7ebc1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":1085,
                "y":111},
              "size":{
                "width":229,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ac1e527f59d4a1fb706c277ab155d49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":111},
                  "size":{
                    "width":229,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "15dbf4f618f6401cab811f32cd63b8e9":{
      "scriptId":"u0"},
    "035d86bfd2374b6b82a3acafc6645997":{
      "scriptId":"u1"},
    "5620bfd5448343ceadffb51e33e88d4c":{
      "scriptId":"u2"},
    "6c001ea800e94daba4ac2c7600eaad2d":{
      "scriptId":"u3"},
    "88113cbf68494cb3a7775334085dab28":{
      "scriptId":"u4",
      "a4f123e0da45458f8e35fb48faba17b1":{
        "scriptId":"u5"},
      "4323b2b3dbc14691ba7216695e5743ff":{
        "scriptId":"u6"},
      "35225ad5f40c42d0bef320eea6b062ad":{
        "scriptId":"u7"},
      "beadbae8d3db479780cfd1f788332f94":{
        "scriptId":"u8"},
      "ae9973c7124c48db8602654217310862":{
        "scriptId":"u9"},
      "6b0816965cb2498d914bd1e5a0f4e8aa":{
        "scriptId":"u10"},
      "e877c7534a5c4e3f9be6321d9a22d45d":{
        "scriptId":"u11"},
      "63d62f61204c41b7bddde3f3d925a12a":{
        "scriptId":"u12"},
      "560656a05b6349818892f9b1ce778f3f":{
        "scriptId":"u13"},
      "4d781244a314498f9245001b6cff2432":{
        "scriptId":"u14"},
      "fb31efab3f774d5fadd72b8053500697":{
        "scriptId":"u15"},
      "ddece461d5d74785aea150665a4ccad8":{
        "scriptId":"u16"},
      "2552a787d0d549a9a07227e8a96cfe7d":{
        "scriptId":"u17"},
      "9b7f8b846c0c4713a4a37db3fc581951":{
        "scriptId":"u18"}},
    "e0efebdec5804e72bc88d9454040e617":{
      "scriptId":"u19"},
    "ea40f4253adb428da8dd4d6ccf3d33c5":{
      "scriptId":"u20"},
    "6293492003f446519c725ef5ca5f9aa4":{
      "scriptId":"u21",
      "1dbc9764fcbc44e4ad363c2678f1b069":{
        "scriptId":"u22"},
      "7abf3b60f2994d22a96b415824ddeb6a":{
        "scriptId":"u23"},
      "25fd79716c9b4affa2bee0a5634583e3":{
        "scriptId":"u24"},
      "8e308b5ba81d4c67aa1834bc5d8e1ab2":{
        "scriptId":"u25"},
      "46eb76913c0441ccb9e141066e3539b2":{
        "scriptId":"u26"},
      "a8fdd90b2d764b56a50c6b57d0f70899":{
        "scriptId":"u27"},
      "b73211a607964d1e9c4b9b9ca1305b78":{
        "scriptId":"u28"},
      "4e7927d5c6e84307adc4e5901413e9fe":{
        "scriptId":"u29"},
      "e4799bc506564ee0a2570f1d9758f91a":{
        "scriptId":"u30"},
      "81434af3de0d4e4dab99e62cf20575b8":{
        "scriptId":"u31"},
      "dbac75afd9474dbaae2adc57fec2dc75":{
        "scriptId":"u32"},
      "17723d194de34772936bdf9bbc9cc1a9":{
        "scriptId":"u33"},
      "859e819d30d0424b93da19cf9dfc811f":{
        "scriptId":"u34"},
      "da35e29e2e9045578f9571b1c098f23e":{
        "scriptId":"u35"},
      "398bd0a3809546b19482b584abcb2d98":{
        "scriptId":"u36"},
      "e862163b6c1649b9aa4a331c26cca7cb":{
        "scriptId":"u37"},
      "efd9cc22b1634b98a88cce427449cc61":{
        "scriptId":"u38"},
      "9bbf5a4d8e2c4525ae4cbcef65fbff5e":{
        "scriptId":"u39"},
      "872978ca3bf84ab0abce826289c2c1ea":{
        "scriptId":"u40"},
      "44957ebe00864e8ab23d78c543b3177e":{
        "scriptId":"u41"}},
    "a4e869781bf740e4bd79ef38a6a5bd07":{
      "scriptId":"u42"},
    "f2182428faaa4fd08a40733c37446330":{
      "scriptId":"u43"},
    "0bf551dab1da4a65adc651f4958368f1":{
      "scriptId":"u44"},
    "9007d45dc3c04691afa68fe8e1977344":{
      "scriptId":"u45"},
    "dcd7d108ecec43f2be05a501979db0f1":{
      "scriptId":"u46"},
    "d6dd99d9a17f42bd844d97fc6f375bb2":{
      "scriptId":"u47"},
    "7b12a4d06bbe47c098e791b7088f4a6b":{
      "scriptId":"u48"},
    "ade9b6fed4a646e2a3f9188e05d6bad9":{
      "scriptId":"u49"},
    "5ef6a4fc0106407ca1e4872baabb7d2d":{
      "scriptId":"u50"},
    "41f98fbf63da44a590311ee9622bb95c":{
      "scriptId":"u51"},
    "5acbc9f3317e4818813f1aa858d4b562":{
      "scriptId":"u52"},
    "59213bbfa8064d5eb98c4ac99bda3490":{
      "scriptId":"u53"},
    "9af237a4ab3741d380558ab002115af8":{
      "scriptId":"u54"},
    "7a14db71e59747efa3e869e83bb0650e":{
      "scriptId":"u55"},
    "9d4a7bab209147249b28e68b63dd3ede":{
      "scriptId":"u56"},
    "bbfba0a46f984284845d1f531b27ec6e":{
      "scriptId":"u57",
      "c73453fa386d40dead74146e04ce954f":{
        "scriptId":"u58"},
      "8878246103114da49b829355f0c5bdae":{
        "scriptId":"u59"},
      "35b1dc1504434f0293e24769738c8e08":{
        "scriptId":"u60"},
      "1f1d119d1ede47d3a712d4b080bbeca8":{
        "scriptId":"u61"},
      "90fa8ef993a6413681691a78c384fde9":{
        "scriptId":"u62"},
      "feb07e2dcb3344d1b08520803a2d24f3":{
        "scriptId":"u63"},
      "626bda77e02f4557abebf86faae7ebc1":{
        "scriptId":"u64"},
      "9ac1e527f59d4a1fb706c277ab155d49":{
        "scriptId":"u65"}},
    "6c180861d641493c875f517b21624406":{
      "scriptId":"u66"},
    "17a85b0a45474c3291230926ed5121de":{
      "scriptId":"u67"},
    "0e65bc8c14d44779834b7913e0ee2e33":{
      "scriptId":"u68"},
    "c702f7140b5249cf919d1acc5826bc66":{
      "scriptId":"u69"},
    "76d54269c73245bfaee946cbdc252bb3":{
      "scriptId":"u70"},
    "977b9dd52fb44dcbb06d26555c3d6545":{
      "scriptId":"u71"}}});