$axure.loadCurrentPage({
  "url":"one_news.html",
  "generationDate":new Date(1378338555169.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"91405fb94eeb427b8a38208d67e74769",
    "type":"Axure:Page",
    "name":"One news",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b5f0112167a402a8a48d6ed234afbd6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"2b09fd4e7d19413c8a1d8ea7fbea1809",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":9,
              "y":137},
            "size":{
              "width":591,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f66af04463470bb0cf9afe56a574a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":9,
                  "y":137},
                "size":{
                  "width":591,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"075485b4fba34f2b9f4f62a8eaac8fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":206},
            "size":{
              "width":590,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f5d1b0f0014f7a9fa7cd05519faa03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":206},
                "size":{
                  "width":590,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61df1e949fb740ce91c74d75cb24472b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":362},
            "size":{
              "width":439,
              "height":231}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f5252be413542869ff127441df5449d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":362},
                "size":{
                  "width":439,
                  "height":231}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/one_news/u21.png"}},
{
          "id":"70232a87ab574b0299b11e55f508f002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":608},
            "size":{
              "width":590,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d48454017ecb4354858d08f39b8563cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":608},
                "size":{
                  "width":590,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3871445906364558836d8c43a7490ba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":631,
              "y":141},
            "size":{
              "width":319,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c8aa7117f684a0d896a46f8d6bf54cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":631,
                  "y":141},
                "size":{
                  "width":319,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"bb5b9aced0924735a6bbcb4f88cb8640",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":631,
              "y":284},
            "size":{
              "width":319,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0db15e87114b629caaeb4c91dae149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":631,
                  "y":284},
                "size":{
                  "width":319,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"551d548cd8d04744ad60f8322918056e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":631,
              "y":428},
            "size":{
              "width":319,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c7f754aaf154fa0b6a064264d018f92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":631,
                  "y":428},
                "size":{
                  "width":319,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One news in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"c5dec4a7656544219a40eccbdfb07036",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":630,
              "y":108},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da901a22f3af4e35854267649ff3b2b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":630,
                  "y":108},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5319c6a46ca4439a011756f2533db3c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":651,
              "y":173}},
          "adaptiveStyles":{
},
          "masterId":"eeb13c352dab4b18b8d45a968d13e7eb"},
{
          "id":"3f3f250e71294e54b2f6bb0f154c0939",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":651,
              "y":316}},
          "adaptiveStyles":{
},
          "masterId":"eeb13c352dab4b18b8d45a968d13e7eb"},
{
          "id":"8d022c99a87e44c0b52de6295483194e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":651,
              "y":460}},
          "adaptiveStyles":{
},
          "masterId":"eeb13c352dab4b18b8d45a968d13e7eb"},
{
          "id":"8da30c7b82604a2581811ee1f94d8586",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":781}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"4fc9df3eb7c64dd5a55a6bde29ac7cbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":693},
            "size":{
              "width":478,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"782e8f83d0d04ae1956c64a8342962e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":693},
                "size":{
                  "width":478,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/one_event/u67.png"}},
{
          "id":"54bfa8c51efb45e6983999dc925d12e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":10,
              "y":108},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"784583e7479e457eb42055caf061ec07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":10,
                  "y":108},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Events in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"events.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "eeb13c352dab4b18b8d45a968d13e7eb":{
      "packageId":"eeb13c352dab4b18b8d45a968d13e7eb",
      "type":"Axure:Master",
      "name":"Превью новости",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a026e81074424a60bf05ab69d75c82fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":260,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa10f14c7b7a4eab8c6c2109ab445b87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":260,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open One news in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"one_news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u88.png",
              "normal~":"images/home/u88.png",
              "normal~":"images/home/u88.png"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png"}}]}}},
  "objectPaths":{
    "1b5f0112167a402a8a48d6ed234afbd6":{
      "scriptId":"u0",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u1"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u2"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u3"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u4"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u5"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u6"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u7"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u8"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u9"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u10"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u11"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u12"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u13"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u14"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u15"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u16"}},
    "2b09fd4e7d19413c8a1d8ea7fbea1809":{
      "scriptId":"u17"},
    "a4f66af04463470bb0cf9afe56a574a3":{
      "scriptId":"u18"},
    "075485b4fba34f2b9f4f62a8eaac8fe7":{
      "scriptId":"u19"},
    "f8f5d1b0f0014f7a9fa7cd05519faa03":{
      "scriptId":"u20"},
    "61df1e949fb740ce91c74d75cb24472b":{
      "scriptId":"u21"},
    "5f5252be413542869ff127441df5449d":{
      "scriptId":"u22"},
    "70232a87ab574b0299b11e55f508f002":{
      "scriptId":"u23"},
    "d48454017ecb4354858d08f39b8563cd":{
      "scriptId":"u24"},
    "3871445906364558836d8c43a7490ba4":{
      "scriptId":"u25"},
    "9c8aa7117f684a0d896a46f8d6bf54cc":{
      "scriptId":"u26"},
    "bb5b9aced0924735a6bbcb4f88cb8640":{
      "scriptId":"u27"},
    "1b0db15e87114b629caaeb4c91dae149":{
      "scriptId":"u28"},
    "551d548cd8d04744ad60f8322918056e":{
      "scriptId":"u29"},
    "4c7f754aaf154fa0b6a064264d018f92":{
      "scriptId":"u30"},
    "c5dec4a7656544219a40eccbdfb07036":{
      "scriptId":"u31"},
    "da901a22f3af4e35854267649ff3b2b8":{
      "scriptId":"u32"},
    "e5319c6a46ca4439a011756f2533db3c":{
      "scriptId":"u33",
      "a026e81074424a60bf05ab69d75c82fe":{
        "scriptId":"u34"},
      "fa10f14c7b7a4eab8c6c2109ab445b87":{
        "scriptId":"u35"}},
    "3f3f250e71294e54b2f6bb0f154c0939":{
      "scriptId":"u36",
      "a026e81074424a60bf05ab69d75c82fe":{
        "scriptId":"u37"},
      "fa10f14c7b7a4eab8c6c2109ab445b87":{
        "scriptId":"u38"}},
    "8d022c99a87e44c0b52de6295483194e":{
      "scriptId":"u39",
      "a026e81074424a60bf05ab69d75c82fe":{
        "scriptId":"u40"},
      "fa10f14c7b7a4eab8c6c2109ab445b87":{
        "scriptId":"u41"}},
    "8da30c7b82604a2581811ee1f94d8586":{
      "scriptId":"u42",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u43"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u44"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u45"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u46"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u47"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u48"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u49"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u50"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u51"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u52"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u53"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u54"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u55"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u56"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u57"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u58"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u59"}},
    "4fc9df3eb7c64dd5a55a6bde29ac7cbe":{
      "scriptId":"u60"},
    "782e8f83d0d04ae1956c64a8342962e1":{
      "scriptId":"u61"},
    "54bfa8c51efb45e6983999dc925d12e0":{
      "scriptId":"u62"},
    "784583e7479e457eb42055caf061ec07":{
      "scriptId":"u63"}}});