$axure.loadCurrentPage({
  "url":"about.html",
  "generationDate":new Date(1378338553248.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69fb226c07384ea2b9ad49a89476f62b",
    "type":"Axure:Page",
    "name":"About",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b9b93c79dd0b4dad90c5417aaf99bcb4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"53399bb13fb54866af9e1ee88ea11cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":9,
              "y":107},
            "size":{
              "width":422,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4478408eec2445da8a21f9fda7ee92ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":9,
                  "y":107},
                "size":{
                  "width":422,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12f56e9c8a5a4ca5b772845b2f35c896",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":147},
            "size":{
              "width":680,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd9b10ccc1d475c9f2ccadb5a6b6f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":147},
                "size":{
                  "width":680,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea6ed85dd6e24bfc88b0de9b27902728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":750,
              "y":111},
            "size":{
              "width":200,
              "height":219}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2424aa6ff4b342f69ecd75806addc701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":750,
                  "y":111},
                "size":{
                  "width":200,
                  "height":219}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u21.png"}},
{
          "id":"f540900c75a64c6a9145f5fab0fba474",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":769,
              "y":163},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c64fa4aa12741128889be350eaa98db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":769,
                  "y":163},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cafe in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cafe.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8627b679d6b4181a14315825087606d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":769,
              "y":194},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2836af25017045ef8e76e7e64076d8f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":769,
                  "y":194},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open For children in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"for_children.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb756c66ea424c26bc8da51b66efcc1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":769,
              "y":224},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b67b0f3435541de9dc93e1d5e230405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":769,
                  "y":224},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b68aed8da7184933b2fdf10aa0c98c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":769,
              "y":255},
            "size":{
              "width":156,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5553801389a847e3ab98a80a6da1df7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":769,
                  "y":255},
                "size":{
                  "width":156,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Host event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"host_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"900d38ac0f16432f9115c6105c016d9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":769,
              "y":285},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"085af2bffe7e44bdbd88cf746179466c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":769,
                  "y":285},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Host event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"host_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f80b1513d5e44d8788c03390dd47c96a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":322},
            "size":{
              "width":560,
              "height":346}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc5cb7e0a3474fd9a4979f9697936bde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":322},
                "size":{
                  "width":560,
                  "height":346}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u33.png"}},
{
          "id":"86e518d6d33b4ccfb7d86214b7ec4558",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":11,
              "y":690},
            "size":{
              "width":159,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7cd98e27cef441c87d697498f48947c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":11,
                  "y":690},
                "size":{
                  "width":159,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u35.png"}},
{
          "id":"1782004fb22549f6bda3d6de7f66c41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":211,
              "y":690},
            "size":{
              "width":159,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"237b1a65a8954423911b42e92fbc1100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":211,
                  "y":690},
                "size":{
                  "width":159,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u35.png"}},
{
          "id":"1c859b313a3441f8bbe60c731df3289c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":411,
              "y":690},
            "size":{
              "width":159,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ccefda619d438087057c5610f6fb84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":411,
                  "y":690},
                "size":{
                  "width":159,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u35.png"}},
{
          "id":"d013b882524946d68ced7a0c8e6f574a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1075}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"a9e7fb3839ab48148a126e3e618fbcbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":823},
            "size":{
              "width":679,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff4f17e9b8042e681881d29f168020b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":823},
                "size":{
                  "width":679,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93e83bbfd07f4a5b91c7be3f5344eb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":769,
              "y":133},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"135e7adb86474076b5d97ed5d155a3c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":769,
                  "y":133},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png"}}]}}},
  "objectPaths":{
    "b9b93c79dd0b4dad90c5417aaf99bcb4":{
      "scriptId":"u0",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u1"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u2"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u3"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u4"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u5"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u6"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u7"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u8"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u9"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u10"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u11"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u12"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u13"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u14"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u15"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u16"}},
    "53399bb13fb54866af9e1ee88ea11cdd":{
      "scriptId":"u17"},
    "4478408eec2445da8a21f9fda7ee92ea":{
      "scriptId":"u18"},
    "12f56e9c8a5a4ca5b772845b2f35c896":{
      "scriptId":"u19"},
    "7bd9b10ccc1d475c9f2ccadb5a6b6f94":{
      "scriptId":"u20"},
    "ea6ed85dd6e24bfc88b0de9b27902728":{
      "scriptId":"u21"},
    "2424aa6ff4b342f69ecd75806addc701":{
      "scriptId":"u22"},
    "f540900c75a64c6a9145f5fab0fba474":{
      "scriptId":"u23"},
    "3c64fa4aa12741128889be350eaa98db":{
      "scriptId":"u24"},
    "f8627b679d6b4181a14315825087606d":{
      "scriptId":"u25"},
    "2836af25017045ef8e76e7e64076d8f6":{
      "scriptId":"u26"},
    "cb756c66ea424c26bc8da51b66efcc1a":{
      "scriptId":"u27"},
    "8b67b0f3435541de9dc93e1d5e230405":{
      "scriptId":"u28"},
    "b68aed8da7184933b2fdf10aa0c98c7f":{
      "scriptId":"u29"},
    "5553801389a847e3ab98a80a6da1df7b":{
      "scriptId":"u30"},
    "900d38ac0f16432f9115c6105c016d9b":{
      "scriptId":"u31"},
    "085af2bffe7e44bdbd88cf746179466c":{
      "scriptId":"u32"},
    "f80b1513d5e44d8788c03390dd47c96a":{
      "scriptId":"u33"},
    "dc5cb7e0a3474fd9a4979f9697936bde":{
      "scriptId":"u34"},
    "86e518d6d33b4ccfb7d86214b7ec4558":{
      "scriptId":"u35"},
    "a7cd98e27cef441c87d697498f48947c":{
      "scriptId":"u36"},
    "1782004fb22549f6bda3d6de7f66c41d":{
      "scriptId":"u37"},
    "237b1a65a8954423911b42e92fbc1100":{
      "scriptId":"u38"},
    "1c859b313a3441f8bbe60c731df3289c":{
      "scriptId":"u39"},
    "56ccefda619d438087057c5610f6fb84":{
      "scriptId":"u40"},
    "d013b882524946d68ced7a0c8e6f574a":{
      "scriptId":"u41",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u42"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u43"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u44"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u45"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u46"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u47"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u48"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u49"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u50"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u51"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u52"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u53"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u54"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u55"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u56"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u57"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u58"}},
    "a9e7fb3839ab48148a126e3e618fbcbd":{
      "scriptId":"u59"},
    "6ff4f17e9b8042e681881d29f168020b":{
      "scriptId":"u60"},
    "93e83bbfd07f4a5b91c7be3f5344eb0f":{
      "scriptId":"u61"},
    "135e7adb86474076b5d97ed5d155a3c9":{
      "scriptId":"u62"}}});