$axure.loadCurrentPage({
  "url":"album.html",
  "generationDate":new Date(1378338556219.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"281b81dce4404732a358dc19b03d5d75",
    "type":"Axure:Page",
    "name":"Album",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d89a78de640e41438e68a1679aae5bdf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c199a18787224c93b11ac9f0472e71b7"},
{
          "id":"4370d3c7974c46a29ac1bc2d40b4ec8e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":530}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"7cc70144493143ca9642b68c1550a0b2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":335}},
          "adaptiveStyles":{
},
          "masterId":"0e8fe2aefb2041cb97f94a1f42a7f99f"},
{
          "id":"ba790ccf431a4a50a9603ff73918714b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":9,
              "y":137},
            "size":{
              "width":591,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e06aacedf14c4f40a89d92faf09789ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":9,
                  "y":137},
                "size":{
                  "width":591,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9e5f695b36640bb8e2f2b02e31a18e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":260},
            "size":{
              "width":593,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09429154a1894ce984034e2ae665eef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":260},
                "size":{
                  "width":593,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c07d022d714447fa71876fff5699709",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1161}},
          "adaptiveStyles":{
},
          "masterId":"ccb8964f59354f4b854fabb8eaddbeab"},
{
          "id":"dcf49afec82d4636bd33a1fb0ce11d2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":217},
            "size":{
              "width":478,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bc3c59c1e17445ea1d50d544f5cd43d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":217},
                "size":{
                  "width":478,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/one_event/u67.png"}},
{
          "id":"f99851b69d224165bf22a1c49008539a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":808,
              "y":108},
            "size":{
              "width":142,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acda629a594b496aa734a57af26018bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":808,
                  "y":108},
                "size":{
                  "width":142,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open One event in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"one_event.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ff9a3feb47f4ac29ebce7721c96bfd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":10,
              "y":108},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b7916d5cc144f4bb5067b50b0dd1a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":10,
                  "y":108},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Media in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"media.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c199a18787224c93b11ac9f0472e71b7":{
      "packageId":"c199a18787224c93b11ac9f0472e71b7",
      "type":"Axure:Master",
      "name":"Шапка",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9df4b231cbb54642b9b75a581d024453",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":966,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c98dacd7fa434d3b9d96585cf9cdd8b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":966,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fc984ed465cf4885ae498a2abe5e4188",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":800,
                "y":20},
              "size":{
                "width":150,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4461d558dd4a4d73900f2de0e78b5eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":800,
                    "y":20},
                  "size":{
                    "width":150,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"305dff17973447f5bec991899b3e2980",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":555,
                "y":37},
              "size":{
                "width":118,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33354a06e36f478fafdf0bb7ac468c8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":555,
                    "y":37},
                  "size":{
                    "width":118,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"49e31d4628b049918ab70c53d3b3f0a3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":438,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92c3f71895cc4a3b882bde22b7e4eac4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":438,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Media in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"media.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"0f8aac2a4b864d1b882dd000afb84f90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":306,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3dc903bab3a443b86cfb89628a66e70",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":306,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tenants in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tenants.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"6a1cfc2ceeff4730a5e22f5ea55e049c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":160,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c0df77bf596492e808ddab68fa75ea6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":160,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d51a131ff2e54bb8904421dd09264186",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "horizontalAlignment":"center",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":37},
              "size":{
                "width":119,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80e7a557d58a4e9ba859bc245f3ee0d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "horizontalAlignment":"center",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":37},
                  "size":{
                    "width":119,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"d04cc3dedd5541f595edc691d58f1335",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":669,
                "y":30},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1847fcafaa6d4bc2b8b22022acc8314f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":669,
                    "y":30},
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}}]}},
    "ccb8964f59354f4b854fabb8eaddbeab":{
      "packageId":"ccb8964f59354f4b854fabb8eaddbeab",
      "type":"Axure:Master",
      "name":"Подвал",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8de2f37e904a42a99a12bbd166aedf73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":-19,
                "y":150},
              "size":{
                "width":960,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"224e11166e104b47bc796ca4e246aae7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":-19,
                    "y":150},
                  "size":{
                    "width":960,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u93.png",
              "normal~":"images/home/u93.png"}},
{
            "id":"91d1ef79f7c54c3281ca7c7e0bc5723b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":10,
                "y":170},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd317d393034cc4967b54e0cb31a786",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":10,
                    "y":170},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u95.png",
              "normal~":"images/home/u95.png"}},
{
            "id":"3a842887323e41e3a1c45fb6a27b5dc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":191,
                "y":170},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"88e998735f374858a2c57495691e3601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":191,
                    "y":170},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0c0fd5e130347daad54e154899861ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":637,
                "y":170},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6ea45ea47d94754b101effbd3fb2886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":637,
                    "y":170},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38dd381f13424c128812fd7c553e3fc9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":421,
                "y":170},
              "size":{
                "width":173,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31455d2be16d42b6b4efab5b9130c2a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":421,
                    "y":170},
                  "size":{
                    "width":173,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Host event in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"host_event.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"597344b5aea24e1e8587100aa2205e9b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "location":{
                "x":309,
                "y":170},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fc994dcc0154496a59cb4ad948f9079",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "location":{
                    "x":309,
                    "y":170},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Rent office in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"rent_office.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c564596e9c8f467fae4571754147911f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":166},
              "size":{
                "width":130,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"5e769d2c39ab49358cfd887c79123455",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":811,
                "y":195},
              "size":{
                "width":79,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97b26624bf464ac786bb56d11e925788",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":811,
                    "y":195},
                  "size":{
                    "width":79,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aea7128fa4ea4a6697f38cdc37e66793",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":170},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54b69e82cee24046b86a6f1d0b0bef3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":170},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u108.png",
              "normal~":"images/home/u108.png"}}]}},
    "0e8fe2aefb2041cb97f94a1f42a7f99f":{
      "packageId":"0e8fe2aefb2041cb97f94a1f42a7f99f",
      "type":"Axure:Master",
      "name":"Шаблон альбома",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03ea334c276f4dcf9cf85bb2a9272604",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac02058bcc494245bffb79769e8866a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":10},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u36.png"}},
{
            "id":"9793642a0b984957b0365213f466efa2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":10},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e7603f0bdda496bbb5c7b980c7f9c82",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":192,
                    "y":10},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"064208aa13174f20af5b17ba22cb56c8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":384,
                "y":10},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7573b686ce5477f9b8e3f99c52f455d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":384,
                    "y":10},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"8f09494c137b4e0fb72f68fdb7979e59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":576,
                "y":10},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cbf88c3a5bd948c7b6c62bd8db3a9046",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":576,
                    "y":10},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"e4a0c87adffb4978bc5b0167884a76dc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":201},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5c2fc896582423f910e4d2b96f9382e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":201},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"df231d1c0c6f43fea0c25fc947504001",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":201},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b557864dbf444fa397527fb4bd7e42c1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":192,
                    "y":201},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"b7a9a008ae4e49818d6b601a44ce55f1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":384,
                "y":201},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe4c304f872f48a99f9a6914d7814301",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":384,
                    "y":201},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u36.png"}},
{
            "id":"177b3e3d4ca94e91b9cddc0aac3b14a1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":576,
                "y":201},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33a12e5661104fb9b0c76453babb9c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":576,
                    "y":201},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"749241e19bb443bab86c44f899b27ac8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":768,
                "y":201},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23ab286af89849efbb562c53c8c0a635",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":768,
                    "y":201},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u36.png"}},
{
            "id":"30c5af338ee84f73ba8eead89a77b5fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":768,
                "y":10},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54cfb1db82a444988a4e5a4b5f7a7511",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":768,
                    "y":10},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"fa96e460c441470c9e05e35f4a579066",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":392},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2486ffccd80542d2aca9fa30a321778e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":392},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"b2212e4eef40405787cec76d0089b30a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":392},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"713b3906dab8464e98895a07b28c3ed8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":192,
                    "y":392},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"9073252c4cc54b419213d1b6bd760a9a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":384,
                "y":392},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"26ee11af47f447f38316b584cfaf333e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":384,
                    "y":392},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"fb777e4ec7424fe09e9c53294a3e0190",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":576,
                "y":392},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f3c0f9a943f4fa7a1f19c5a0550ecef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":576,
                    "y":392},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"a97a827e2bcc4586a5c065ebd793aeda",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":768,
                "y":392},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81282bd352ba4349a303f70bee43d79f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":768,
                    "y":392},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"19aa7994c0e74f5daecccc420486b360",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":583},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eb6c5767b8b44a5fbaedef1c2d22493f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":583},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"8a3a1418204d4e5ea6a5b997359fbd71",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":583},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee4410dd4fff4257bce1fde113f15d97",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":192,
                    "y":583},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"9be5a3e46d4c49f595c730db89739484",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":384,
                "y":583},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c0196ef8f5054066bc59d33a6e88f6b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":384,
                    "y":583},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"57843e245b924a64a2aa1b553cd38ce9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":576,
                "y":583},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6755e414a33243c4834080daca2b9a79",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":576,
                    "y":583},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}},
{
            "id":"0054ecdff18044fa8004ac4b76b98a26",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":768,
                "y":583},
              "size":{
                "width":192,
                "height":192}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"32e8f6112d314ddc89a94221e2c05fc8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":768,
                    "y":583},
                  "size":{
                    "width":192,
                    "height":192}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/album/u38.png"}}]}}},
  "objectPaths":{
    "d89a78de640e41438e68a1679aae5bdf":{
      "scriptId":"u0",
      "9df4b231cbb54642b9b75a581d024453":{
        "scriptId":"u1"},
      "c98dacd7fa434d3b9d96585cf9cdd8b4":{
        "scriptId":"u2"},
      "fc984ed465cf4885ae498a2abe5e4188":{
        "scriptId":"u3"},
      "4461d558dd4a4d73900f2de0e78b5eeb":{
        "scriptId":"u4"},
      "305dff17973447f5bec991899b3e2980":{
        "scriptId":"u5"},
      "33354a06e36f478fafdf0bb7ac468c8e":{
        "scriptId":"u6"},
      "49e31d4628b049918ab70c53d3b3f0a3":{
        "scriptId":"u7"},
      "92c3f71895cc4a3b882bde22b7e4eac4":{
        "scriptId":"u8"},
      "0f8aac2a4b864d1b882dd000afb84f90":{
        "scriptId":"u9"},
      "e3dc903bab3a443b86cfb89628a66e70":{
        "scriptId":"u10"},
      "6a1cfc2ceeff4730a5e22f5ea55e049c":{
        "scriptId":"u11"},
      "1c0df77bf596492e808ddab68fa75ea6":{
        "scriptId":"u12"},
      "d51a131ff2e54bb8904421dd09264186":{
        "scriptId":"u13"},
      "80e7a557d58a4e9ba859bc245f3ee0d3":{
        "scriptId":"u14"},
      "d04cc3dedd5541f595edc691d58f1335":{
        "scriptId":"u15"},
      "1847fcafaa6d4bc2b8b22022acc8314f":{
        "scriptId":"u16"}},
    "4370d3c7974c46a29ac1bc2d40b4ec8e":{
      "scriptId":"u17",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u18"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u19"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u20"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u21"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u22"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u23"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u24"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u25"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u26"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u27"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u28"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u29"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u30"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u31"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u32"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u33"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u34"}},
    "7cc70144493143ca9642b68c1550a0b2":{
      "scriptId":"u35",
      "03ea334c276f4dcf9cf85bb2a9272604":{
        "scriptId":"u36"},
      "ac02058bcc494245bffb79769e8866a4":{
        "scriptId":"u37"},
      "9793642a0b984957b0365213f466efa2":{
        "scriptId":"u38"},
      "1e7603f0bdda496bbb5c7b980c7f9c82":{
        "scriptId":"u39"},
      "064208aa13174f20af5b17ba22cb56c8":{
        "scriptId":"u40"},
      "c7573b686ce5477f9b8e3f99c52f455d":{
        "scriptId":"u41"},
      "8f09494c137b4e0fb72f68fdb7979e59":{
        "scriptId":"u42"},
      "cbf88c3a5bd948c7b6c62bd8db3a9046":{
        "scriptId":"u43"},
      "e4a0c87adffb4978bc5b0167884a76dc":{
        "scriptId":"u44"},
      "f5c2fc896582423f910e4d2b96f9382e":{
        "scriptId":"u45"},
      "df231d1c0c6f43fea0c25fc947504001":{
        "scriptId":"u46"},
      "b557864dbf444fa397527fb4bd7e42c1":{
        "scriptId":"u47"},
      "b7a9a008ae4e49818d6b601a44ce55f1":{
        "scriptId":"u48"},
      "fe4c304f872f48a99f9a6914d7814301":{
        "scriptId":"u49"},
      "177b3e3d4ca94e91b9cddc0aac3b14a1":{
        "scriptId":"u50"},
      "33a12e5661104fb9b0c76453babb9c08":{
        "scriptId":"u51"},
      "749241e19bb443bab86c44f899b27ac8":{
        "scriptId":"u52"},
      "23ab286af89849efbb562c53c8c0a635":{
        "scriptId":"u53"},
      "30c5af338ee84f73ba8eead89a77b5fc":{
        "scriptId":"u54"},
      "54cfb1db82a444988a4e5a4b5f7a7511":{
        "scriptId":"u55"},
      "fa96e460c441470c9e05e35f4a579066":{
        "scriptId":"u56"},
      "2486ffccd80542d2aca9fa30a321778e":{
        "scriptId":"u57"},
      "b2212e4eef40405787cec76d0089b30a":{
        "scriptId":"u58"},
      "713b3906dab8464e98895a07b28c3ed8":{
        "scriptId":"u59"},
      "9073252c4cc54b419213d1b6bd760a9a":{
        "scriptId":"u60"},
      "26ee11af47f447f38316b584cfaf333e":{
        "scriptId":"u61"},
      "fb777e4ec7424fe09e9c53294a3e0190":{
        "scriptId":"u62"},
      "7f3c0f9a943f4fa7a1f19c5a0550ecef":{
        "scriptId":"u63"},
      "a97a827e2bcc4586a5c065ebd793aeda":{
        "scriptId":"u64"},
      "81282bd352ba4349a303f70bee43d79f":{
        "scriptId":"u65"},
      "19aa7994c0e74f5daecccc420486b360":{
        "scriptId":"u66"},
      "eb6c5767b8b44a5fbaedef1c2d22493f":{
        "scriptId":"u67"},
      "8a3a1418204d4e5ea6a5b997359fbd71":{
        "scriptId":"u68"},
      "ee4410dd4fff4257bce1fde113f15d97":{
        "scriptId":"u69"},
      "9be5a3e46d4c49f595c730db89739484":{
        "scriptId":"u70"},
      "c0196ef8f5054066bc59d33a6e88f6b7":{
        "scriptId":"u71"},
      "57843e245b924a64a2aa1b553cd38ce9":{
        "scriptId":"u72"},
      "6755e414a33243c4834080daca2b9a79":{
        "scriptId":"u73"},
      "0054ecdff18044fa8004ac4b76b98a26":{
        "scriptId":"u74"},
      "32e8f6112d314ddc89a94221e2c05fc8":{
        "scriptId":"u75"}},
    "ba790ccf431a4a50a9603ff73918714b":{
      "scriptId":"u76"},
    "e06aacedf14c4f40a89d92faf09789ff":{
      "scriptId":"u77"},
    "e9e5f695b36640bb8e2f2b02e31a18e0":{
      "scriptId":"u78"},
    "09429154a1894ce984034e2ae665eef4":{
      "scriptId":"u79"},
    "6c07d022d714447fa71876fff5699709":{
      "scriptId":"u80",
      "8de2f37e904a42a99a12bbd166aedf73":{
        "scriptId":"u81"},
      "224e11166e104b47bc796ca4e246aae7":{
        "scriptId":"u82"},
      "91d1ef79f7c54c3281ca7c7e0bc5723b":{
        "scriptId":"u83"},
      "6fd317d393034cc4967b54e0cb31a786":{
        "scriptId":"u84"},
      "3a842887323e41e3a1c45fb6a27b5dc4":{
        "scriptId":"u85"},
      "88e998735f374858a2c57495691e3601":{
        "scriptId":"u86"},
      "c0c0fd5e130347daad54e154899861ec":{
        "scriptId":"u87"},
      "c6ea45ea47d94754b101effbd3fb2886":{
        "scriptId":"u88"},
      "38dd381f13424c128812fd7c553e3fc9":{
        "scriptId":"u89"},
      "31455d2be16d42b6b4efab5b9130c2a2":{
        "scriptId":"u90"},
      "597344b5aea24e1e8587100aa2205e9b":{
        "scriptId":"u91"},
      "5fc994dcc0154496a59cb4ad948f9079":{
        "scriptId":"u92"},
      "c564596e9c8f467fae4571754147911f":{
        "scriptId":"u93"},
      "5e769d2c39ab49358cfd887c79123455":{
        "scriptId":"u94"},
      "97b26624bf464ac786bb56d11e925788":{
        "scriptId":"u95"},
      "aea7128fa4ea4a6697f38cdc37e66793":{
        "scriptId":"u96"},
      "54b69e82cee24046b86a6f1d0b0bef3b":{
        "scriptId":"u97"}},
    "dcf49afec82d4636bd33a1fb0ce11d2f":{
      "scriptId":"u98"},
    "6bc3c59c1e17445ea1d50d544f5cd43d":{
      "scriptId":"u99"},
    "f99851b69d224165bf22a1c49008539a":{
      "scriptId":"u100"},
    "acda629a594b496aa734a57af26018bd":{
      "scriptId":"u101"},
    "2ff9a3feb47f4ac29ebce7721c96bfd1":{
      "scriptId":"u102"},
    "0b7916d5cc144f4bb5067b50b0dd1a4a":{
      "scriptId":"u103"}}});