$axure.loadCurrentPage({
  "url":"join.html",
  "generationDate":new Date(1382378689056.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"24bb0d2b9ce64a19bd9eff04f1844f2e",
    "type":"Axure:Page",
    "name":"Join",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2783547c7a6c46b587b15cd2337076bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":100,
              "y":317},
            "size":{
              "width":630,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b83f7b43c4e453fbf44870fd7e89d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":100,
                  "y":317},
                "size":{
                  "width":630,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e970336f8e2846738e7b4eedd112d83e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "lineSpacing":"48px",
            "location":{
              "x":100,
              "y":207},
            "size":{
              "width":727,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a450759e4564f02900867ee9d2fe932",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "lineSpacing":"48px",
                "location":{
                  "x":100,
                  "y":207},
                "size":{
                  "width":727,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca1b2163fd6e4b6f9024b89fb1b01f56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":924,
              "y":242},
            "size":{
              "width":366,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d241443fabca477190281654fe35595f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":924,
                  "y":242},
                "size":{
                  "width":366,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3341994633c7422eafb8670992a282d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":925,
              "y":220},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7881c34901ba49378f672cd2ead56f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":925,
                  "y":220},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0e567e0326b43dc9c2e612d04fc9325",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "lineSpacing":"28px",
            "location":{
              "x":100,
              "y":142},
            "size":{
              "width":320,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afcca55652a4b04b2738ca22b4e0b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "lineSpacing":"28px",
                "location":{
                  "x":100,
                  "y":142},
                "size":{
                  "width":320,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fb05aa650d5461ca4d5e6cb9f9daf98",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":710}},
          "adaptiveStyles":{
},
          "masterId":"922385ae9a2e4795bce54b3d94957db1"},
{
          "id":"72440303fc4d4934aedafbba2ac69073",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":31}},
          "adaptiveStyles":{
},
          "masterId":"4003f31f2bf74a6e960c609db1aebe89"},
{
          "id":"2ed8ceed33124322b99c9abaff9b6be1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":100,
              "y":556},
            "size":{
              "width":630,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9446ff0a2d4dc2a19ecd0252304cb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":100,
                  "y":556},
                "size":{
                  "width":630,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c84cddcbde014b8e9fdd5f957b641af6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "lineSpacing":"48px",
            "location":{
              "x":100,
              "y":446},
            "size":{
              "width":727,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc3609de6f8e4e74a5d996e7bef43da9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "lineSpacing":"48px",
                "location":{
                  "x":100,
                  "y":446},
                "size":{
                  "width":727,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40b76caaf55d4626aaa524d0257b488c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":925,
              "y":480},
            "size":{
              "width":366,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476c9e84e5a5413b81b01c7a9e2f2feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":925,
                  "y":480},
                "size":{
                  "width":366,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec154649a58f403b88973e5b63cbf911",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":926,
              "y":458},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c85865af55c34339a4ba89cd5c4f46fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":926,
                  "y":458},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27babc6584324a3ebdcd11e209f02571",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":924,
              "y":317},
            "size":{
              "width":310,
              "height":51},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b8c6be73f8c4aefa6c35ee1728a34a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":924,
                  "y":317},
                "size":{
                  "width":310,
                  "height":51},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/join/u48.png"}},
{
          "id":"cd957998180a4e48af187b96b087729c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":996,
              "y":327},
            "size":{
              "width":186,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873d6010fd304637aa1bc0608a5d5250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":996,
                  "y":327},
                "size":{
                  "width":186,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open In Soyze in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"in_soyze.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2629111183734dba8755f2c40ae7844e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":925,
              "y":560},
            "size":{
              "width":345,
              "height":51},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f6b01c22be144efaa13aab63b698ed4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":925,
                  "y":560},
                "size":{
                  "width":345,
                  "height":51},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/join/u52.png"}},
{
          "id":"a9bbd291e8d54242be0a47344f01456f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":945,
              "y":570},
            "size":{
              "width":305,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae0ccaef0a6340bf95b528aa74cde509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":945,
                  "y":570},
                "size":{
                  "width":305,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Join_Form in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"join_form.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "922385ae9a2e4795bce54b3d94957db1":{
      "packageId":"922385ae9a2e4795bce54b3d94957db1",
      "type":"Axure:Master",
      "name":"end",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c73453fa386d40dead74146e04ce954f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7FF2F2F2},
              "size":{
                "width":1410,
                "height":230},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8878246103114da49b829355f0c5bdae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7FF2F2F2},
                  "size":{
                    "width":1410,
                    "height":230},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u3.png"}},
{
            "id":"35b1dc1504434f0293e24769738c8e08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":100,
                "y":111},
              "size":{
                "width":519,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f1d119d1ede47d3a712d4b080bbeca8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":111},
                  "size":{
                    "width":519,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fa8ef993a6413681691a78c384fde9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF949494,
                "opacity":1},
              "location":{
                "x":100,
                "y":40},
              "size":{
                "width":1250,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"feb07e2dcb3344d1b08520803a2d24f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF949494,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":40},
                  "size":{
                    "width":1250,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"626bda77e02f4557abebf86faae7ebc1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":1085,
                "y":111},
              "size":{
                "width":229,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ac1e527f59d4a1fb706c277ab155d49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":111},
                  "size":{
                    "width":229,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "4003f31f2bf74a6e960c609db1aebe89":{
      "packageId":"4003f31f2bf74a6e960c609db1aebe89",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1dbc9764fcbc44e4ad363c2678f1b069",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":849,
                "y":26},
              "size":{
                "width":140,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7abf3b60f2994d22a96b415824ddeb6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":849,
                    "y":26},
                  "size":{
                    "width":140,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u12.png"}},
{
            "id":"25fd79716c9b4affa2bee0a5634583e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":179,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e308b5ba81d4c67aa1834bc5d8e1ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":179,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home_page in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home_page.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"46eb76913c0441ccb9e141066e3539b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":229,
                "y":30},
              "size":{
                "width":120,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8fdd90b2d764b56a50c6b57d0f70899",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":229,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b73211a607964d1e9c4b9b9ca1305b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":386,
                "y":30},
              "size":{
                "width":84,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e7927d5c6e84307adc4e5901413e9fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":386,
                    "y":30},
                  "size":{
                    "width":84,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4799bc506564ee0a2570f1d9758f91a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":611,
                "y":30},
              "size":{
                "width":90,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81434af3de0d4e4dab99e62cf20575b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":611,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Projects in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"projects.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbac75afd9474dbaae2adc57fec2dc75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":728,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17723d194de34772936bdf9bbc9cc1a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":728,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"859e819d30d0424b93da19cf9dfc811f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":875,
                "y":29},
              "size":{
                "width":104,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da35e29e2e9045578f9571b1c098f23e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":875,
                    "y":29},
                  "size":{
                    "width":104,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Join in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"join.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"398bd0a3809546b19482b584abcb2d98",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "lineSpacing":"18px",
              "location":{
                "x":1130,
                "y":37},
              "size":{
                "width":59,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e862163b6c1649b9aa4a331c26cca7cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1130,
                    "y":37},
                  "size":{
                    "width":59,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Subscription in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"subscription.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"efd9cc22b1634b98a88cce427449cc61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "lineSpacing":"18px",
              "location":{
                "x":1013,
                "y":38},
              "size":{
                "width":117,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bbf5a4d8e2c4525ae4cbcef65fbff5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1013,
                    "y":38},
                  "size":{
                    "width":117,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872978ca3bf84ab0abce826289c2c1ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":506,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44957ebe00864e8ab23d78c543b3177e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":506,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2783547c7a6c46b587b15cd2337076bf":{
      "scriptId":"u0"},
    "0b83f7b43c4e453fbf44870fd7e89d73":{
      "scriptId":"u1"},
    "e970336f8e2846738e7b4eedd112d83e":{
      "scriptId":"u2"},
    "4a450759e4564f02900867ee9d2fe932":{
      "scriptId":"u3"},
    "ca1b2163fd6e4b6f9024b89fb1b01f56":{
      "scriptId":"u4"},
    "d241443fabca477190281654fe35595f":{
      "scriptId":"u5"},
    "3341994633c7422eafb8670992a282d2":{
      "scriptId":"u6"},
    "7881c34901ba49378f672cd2ead56f45":{
      "scriptId":"u7"},
    "c0e567e0326b43dc9c2e612d04fc9325":{
      "scriptId":"u8"},
    "7afcca55652a4b04b2738ca22b4e0b27":{
      "scriptId":"u9"},
    "7fb05aa650d5461ca4d5e6cb9f9daf98":{
      "scriptId":"u10",
      "c73453fa386d40dead74146e04ce954f":{
        "scriptId":"u11"},
      "8878246103114da49b829355f0c5bdae":{
        "scriptId":"u12"},
      "35b1dc1504434f0293e24769738c8e08":{
        "scriptId":"u13"},
      "1f1d119d1ede47d3a712d4b080bbeca8":{
        "scriptId":"u14"},
      "90fa8ef993a6413681691a78c384fde9":{
        "scriptId":"u15"},
      "feb07e2dcb3344d1b08520803a2d24f3":{
        "scriptId":"u16"},
      "626bda77e02f4557abebf86faae7ebc1":{
        "scriptId":"u17"},
      "9ac1e527f59d4a1fb706c277ab155d49":{
        "scriptId":"u18"}},
    "72440303fc4d4934aedafbba2ac69073":{
      "scriptId":"u19",
      "1dbc9764fcbc44e4ad363c2678f1b069":{
        "scriptId":"u20"},
      "7abf3b60f2994d22a96b415824ddeb6a":{
        "scriptId":"u21"},
      "25fd79716c9b4affa2bee0a5634583e3":{
        "scriptId":"u22"},
      "8e308b5ba81d4c67aa1834bc5d8e1ab2":{
        "scriptId":"u23"},
      "46eb76913c0441ccb9e141066e3539b2":{
        "scriptId":"u24"},
      "a8fdd90b2d764b56a50c6b57d0f70899":{
        "scriptId":"u25"},
      "b73211a607964d1e9c4b9b9ca1305b78":{
        "scriptId":"u26"},
      "4e7927d5c6e84307adc4e5901413e9fe":{
        "scriptId":"u27"},
      "e4799bc506564ee0a2570f1d9758f91a":{
        "scriptId":"u28"},
      "81434af3de0d4e4dab99e62cf20575b8":{
        "scriptId":"u29"},
      "dbac75afd9474dbaae2adc57fec2dc75":{
        "scriptId":"u30"},
      "17723d194de34772936bdf9bbc9cc1a9":{
        "scriptId":"u31"},
      "859e819d30d0424b93da19cf9dfc811f":{
        "scriptId":"u32"},
      "da35e29e2e9045578f9571b1c098f23e":{
        "scriptId":"u33"},
      "398bd0a3809546b19482b584abcb2d98":{
        "scriptId":"u34"},
      "e862163b6c1649b9aa4a331c26cca7cb":{
        "scriptId":"u35"},
      "efd9cc22b1634b98a88cce427449cc61":{
        "scriptId":"u36"},
      "9bbf5a4d8e2c4525ae4cbcef65fbff5e":{
        "scriptId":"u37"},
      "872978ca3bf84ab0abce826289c2c1ea":{
        "scriptId":"u38"},
      "44957ebe00864e8ab23d78c543b3177e":{
        "scriptId":"u39"}},
    "2ed8ceed33124322b99c9abaff9b6be1":{
      "scriptId":"u40"},
    "5d9446ff0a2d4dc2a19ecd0252304cb4":{
      "scriptId":"u41"},
    "c84cddcbde014b8e9fdd5f957b641af6":{
      "scriptId":"u42"},
    "fc3609de6f8e4e74a5d996e7bef43da9":{
      "scriptId":"u43"},
    "40b76caaf55d4626aaa524d0257b488c":{
      "scriptId":"u44"},
    "476c9e84e5a5413b81b01c7a9e2f2feb":{
      "scriptId":"u45"},
    "ec154649a58f403b88973e5b63cbf911":{
      "scriptId":"u46"},
    "c85865af55c34339a4ba89cd5c4f46fe":{
      "scriptId":"u47"},
    "27babc6584324a3ebdcd11e209f02571":{
      "scriptId":"u48"},
    "7b8c6be73f8c4aefa6c35ee1728a34a4":{
      "scriptId":"u49"},
    "cd957998180a4e48af187b96b087729c":{
      "scriptId":"u50"},
    "873d6010fd304637aa1bc0608a5d5250":{
      "scriptId":"u51"},
    "2629111183734dba8755f2c40ae7844e":{
      "scriptId":"u52"},
    "7f6b01c22be144efaa13aab63b698ed4":{
      "scriptId":"u53"},
    "a9bbd291e8d54242be0a47344f01456f":{
      "scriptId":"u54"},
    "ae0ccaef0a6340bf95b528aa74cde509":{
      "scriptId":"u55"}}});