$axure.loadCurrentPage({
  "url":"event.html",
  "generationDate":new Date(1382378688092.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bbd2c54635d64c3e820712e6d18c218b",
    "type":"Axure:Page",
    "name":"Event",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9cd78dbd871f46e9ba24bb5b90eac517",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FF2F2F2},
            "location":{
              "x":0,
              "y":111},
            "size":{
              "width":1410,
              "height":459},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cd524c9b9bc4689aee53cc68f079cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FF2F2F2},
                "location":{
                  "x":0,
                  "y":111},
                "size":{
                  "width":1410,
                  "height":459},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event/u0.png"}},
{
          "id":"ce0cc33ac2244391b4adaa9ed20b6109",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "lineSpacing":"36px",
            "location":{
              "x":379,
              "y":232},
            "size":{
              "width":629,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e288a141b2409887b78e7109663b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "lineSpacing":"36px",
                "location":{
                  "x":379,
                  "y":232},
                "size":{
                  "width":629,
                  "height":154}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be3f8027543c4af3a8bddb7e80528901",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":28}},
          "adaptiveStyles":{
},
          "masterId":"4003f31f2bf74a6e960c609db1aebe89"},
{
          "id":"c3ef00bb710240f1adde0de71f5a3adf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":378,
              "y":621},
            "size":{
              "width":170,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09a4218518bb421e88ce63f769054786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":378,
                  "y":621},
                "size":{
                  "width":170,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b5a7ac9262d49be89f5e30a0ce3f0aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":379,
              "y":406},
            "size":{
              "width":601,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f323f84b9564ee79285e9df27d3bae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":379,
                  "y":406},
                "size":{
                  "width":601,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f137130622149c3bc1e567ac73e3f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":100,
              "y":355},
            "size":{
              "width":240,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d84671d9319e4e3eb1241e3d24e9a8ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":100,
                  "y":355},
                "size":{
                  "width":240,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/event/u29.png"}},
{
          "id":"10e6d8e9297842d09e1e16c0559c33ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":180,
              "y":366},
            "size":{
              "width":256,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4576c985565a40ae9005b8d00dffac15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":180,
                  "y":366},
                "size":{
                  "width":256,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b63209e4b463422885f59a677cf1c75d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "lineSpacing":"28px",
            "location":{
              "x":100,
              "y":142},
            "size":{
              "width":280,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a03c203ac7b6407c80aa97be61b1a674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "lineSpacing":"28px",
                "location":{
                  "x":100,
                  "y":142},
                "size":{
                  "width":280,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41dbbc03dcb1464aba0daecca2703f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "lineSpacing":"36px",
            "location":{
              "x":101,
              "y":232},
            "size":{
              "width":239,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc5a6bfafd943499cfb4a00bd335334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "lineSpacing":"36px",
                "location":{
                  "x":101,
                  "y":232},
                "size":{
                  "width":239,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a55584a47d104585a8a7bde591cff85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":100,
              "y":318},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"488d49b7ba66451ebe999a967f509749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":100,
                  "y":318},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46bcfef7d60045e2ad046d6e230ff8bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":378,
              "y":680},
            "size":{
              "width":312,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd518564aceb49e99b6ab852312799a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":378,
                  "y":680},
                "size":{
                  "width":312,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e13dd54f2e884f05b50392451a76b796",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1360}},
          "adaptiveStyles":{
},
          "masterId":"922385ae9a2e4795bce54b3d94957db1"},
{
          "id":"f1e10fe8b8a546899df1ec9fdcd00d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":724,
              "y":621},
            "size":{
              "width":170,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f219a7d1684ea99d00fd3f16d891a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":724,
                  "y":621},
                "size":{
                  "width":170,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4347f1309f04d118fb300bd1aab8776",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":195},
            "size":{
              "width":1189,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/sections/u29_line.png"}},
{
          "id":"78773081445d41eab26e1146b67ef745",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":585},
            "size":{
              "width":880,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/event/u53_line.png"}},
{
          "id":"54667adcca4e477d9c7c3ff007dc04fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":670},
            "size":{
              "width":290,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59934786296464b90498d06daf1e77e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":724,
                  "y":670},
                "size":{
                  "width":290,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u32.png"}},
{
          "id":"2cd15635d278403495794d9d4dc8b8c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":100,
              "y":623},
            "size":{
              "width":200,
              "height":151}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7fcff5d698e458586632652fd5b23ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":100,
                  "y":623},
                "size":{
                  "width":200,
                  "height":151}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8b7958ac5604b1fbbdb8375c4434649",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":142,
              "y":656},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1516162dd0544d7a912798df3433fa44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":142,
                  "y":656},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u71.png"}},
{
          "id":"23996fd9d2864551b9d86f4d55ec90ed",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":684},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bfb016152b04e2895b3358b627f1652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":684},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u73.png"}},
{
          "id":"6b78d3efa3c442408f88b294aca868dd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":150,
              "y":712},
            "size":{
              "width":64,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ab18b2f70d249b2807855e62e588a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":150,
                  "y":712},
                "size":{
                  "width":64,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u75.png"}},
{
          "id":"04817f8209424c4e906c6cc1cde9d2c3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":220,
              "y":712},
            "size":{
              "width":46,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c166ea49f7a040b4a9f6db2082589a9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":220,
                  "y":712},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u77.png"}},
{
          "id":"1cef090bc46245e89254e549106bcb92",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":872},
            "size":{
              "width":880,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/event/u53_line.png"}},
{
          "id":"3b4c5209ff4a480495e1f353784b48cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":217,
              "y":918},
            "size":{
              "width":114,
              "height":113},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac92d3c072fd40039f70158a56ead5b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":217,
                  "y":918},
                "size":{
                  "width":114,
                  "height":113},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_page/u50.png"}},
{
          "id":"fbee8f14b55747f68e25bb2cdce99400",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":378,
              "y":1029},
            "size":{
              "width":683,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc22023a915242c78968d1d0c908b59a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":378,
                  "y":1029},
                "size":{
                  "width":683,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9786cb3a82f249fa9b94bd073a35d6a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":379,
              "y":936},
            "size":{
              "width":461,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df46fe9eade24127b9b22aa17ca6f5d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":379,
                  "y":936},
                "size":{
                  "width":461,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb9bc213aa484f768c0bbda9b3d76265",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":380,
              "y":914},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b88b7ede97c24e0cb2d470fafb302ebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":380,
                  "y":914},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f741ea7487d4ac0ac73f18b18b326dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":379,
              "y":1245},
            "size":{
              "width":670,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d4afcfcdf4a4368969a4d07285a3af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":379,
                  "y":1245},
                "size":{
                  "width":670,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2faa148792a748338fb7b528da7e31eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":380,
              "y":1152},
            "size":{
              "width":461,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bcf32c44e5d4625a554506238e892a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":380,
                  "y":1152},
                "size":{
                  "width":461,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dab0022f1c02448cbb679bf27352bf77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":380,
              "y":1131},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47838270e4194f3388eb857a96405425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":380,
                  "y":1131},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5da46c2ad56148f68f2f4aae5211bcd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":217,
              "y":1141},
            "size":{
              "width":114,
              "height":113},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf75190a2e714ecb9e4100ba0892c063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":217,
                  "y":1141},
                "size":{
                  "width":114,
                  "height":113},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_page/u50.png"}},
{
          "id":"48c0c5160fdb40f5978be7b6fdf4ae63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":100,
              "y":830},
            "size":{
              "width":350,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd568100b1ec420eab7e88a021a7af28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":100,
                  "y":830},
                "size":{
                  "width":350,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4003f31f2bf74a6e960c609db1aebe89":{
      "packageId":"4003f31f2bf74a6e960c609db1aebe89",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1dbc9764fcbc44e4ad363c2678f1b069",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":849,
                "y":26},
              "size":{
                "width":140,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7abf3b60f2994d22a96b415824ddeb6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":849,
                    "y":26},
                  "size":{
                    "width":140,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u12.png"}},
{
            "id":"25fd79716c9b4affa2bee0a5634583e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":179,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e308b5ba81d4c67aa1834bc5d8e1ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":179,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home_page in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home_page.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"46eb76913c0441ccb9e141066e3539b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":229,
                "y":30},
              "size":{
                "width":120,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8fdd90b2d764b56a50c6b57d0f70899",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":229,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b73211a607964d1e9c4b9b9ca1305b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":386,
                "y":30},
              "size":{
                "width":84,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e7927d5c6e84307adc4e5901413e9fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":386,
                    "y":30},
                  "size":{
                    "width":84,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4799bc506564ee0a2570f1d9758f91a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":611,
                "y":30},
              "size":{
                "width":90,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81434af3de0d4e4dab99e62cf20575b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":611,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Projects in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"projects.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbac75afd9474dbaae2adc57fec2dc75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":728,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17723d194de34772936bdf9bbc9cc1a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":728,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"859e819d30d0424b93da19cf9dfc811f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":875,
                "y":29},
              "size":{
                "width":104,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da35e29e2e9045578f9571b1c098f23e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":875,
                    "y":29},
                  "size":{
                    "width":104,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Join in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"join.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"398bd0a3809546b19482b584abcb2d98",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "lineSpacing":"18px",
              "location":{
                "x":1130,
                "y":37},
              "size":{
                "width":59,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e862163b6c1649b9aa4a331c26cca7cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1130,
                    "y":37},
                  "size":{
                    "width":59,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Subscription in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"subscription.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"efd9cc22b1634b98a88cce427449cc61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "lineSpacing":"18px",
              "location":{
                "x":1013,
                "y":38},
              "size":{
                "width":117,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bbf5a4d8e2c4525ae4cbcef65fbff5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1013,
                    "y":38},
                  "size":{
                    "width":117,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872978ca3bf84ab0abce826289c2c1ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":506,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44957ebe00864e8ab23d78c543b3177e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":506,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "922385ae9a2e4795bce54b3d94957db1":{
      "packageId":"922385ae9a2e4795bce54b3d94957db1",
      "type":"Axure:Master",
      "name":"end",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c73453fa386d40dead74146e04ce954f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7FF2F2F2},
              "size":{
                "width":1410,
                "height":230},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8878246103114da49b829355f0c5bdae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7FF2F2F2},
                  "size":{
                    "width":1410,
                    "height":230},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u3.png"}},
{
            "id":"35b1dc1504434f0293e24769738c8e08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":100,
                "y":111},
              "size":{
                "width":519,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f1d119d1ede47d3a712d4b080bbeca8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":111},
                  "size":{
                    "width":519,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fa8ef993a6413681691a78c384fde9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF949494,
                "opacity":1},
              "location":{
                "x":100,
                "y":40},
              "size":{
                "width":1250,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"feb07e2dcb3344d1b08520803a2d24f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF949494,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":40},
                  "size":{
                    "width":1250,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"626bda77e02f4557abebf86faae7ebc1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":1085,
                "y":111},
              "size":{
                "width":229,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ac1e527f59d4a1fb706c277ab155d49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":111},
                  "size":{
                    "width":229,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "9cd78dbd871f46e9ba24bb5b90eac517":{
      "scriptId":"u0"},
    "7cd524c9b9bc4689aee53cc68f079cdb":{
      "scriptId":"u1"},
    "ce0cc33ac2244391b4adaa9ed20b6109":{
      "scriptId":"u2"},
    "54e288a141b2409887b78e7109663b1c":{
      "scriptId":"u3"},
    "be3f8027543c4af3a8bddb7e80528901":{
      "scriptId":"u4",
      "1dbc9764fcbc44e4ad363c2678f1b069":{
        "scriptId":"u5"},
      "7abf3b60f2994d22a96b415824ddeb6a":{
        "scriptId":"u6"},
      "25fd79716c9b4affa2bee0a5634583e3":{
        "scriptId":"u7"},
      "8e308b5ba81d4c67aa1834bc5d8e1ab2":{
        "scriptId":"u8"},
      "46eb76913c0441ccb9e141066e3539b2":{
        "scriptId":"u9"},
      "a8fdd90b2d764b56a50c6b57d0f70899":{
        "scriptId":"u10"},
      "b73211a607964d1e9c4b9b9ca1305b78":{
        "scriptId":"u11"},
      "4e7927d5c6e84307adc4e5901413e9fe":{
        "scriptId":"u12"},
      "e4799bc506564ee0a2570f1d9758f91a":{
        "scriptId":"u13"},
      "81434af3de0d4e4dab99e62cf20575b8":{
        "scriptId":"u14"},
      "dbac75afd9474dbaae2adc57fec2dc75":{
        "scriptId":"u15"},
      "17723d194de34772936bdf9bbc9cc1a9":{
        "scriptId":"u16"},
      "859e819d30d0424b93da19cf9dfc811f":{
        "scriptId":"u17"},
      "da35e29e2e9045578f9571b1c098f23e":{
        "scriptId":"u18"},
      "398bd0a3809546b19482b584abcb2d98":{
        "scriptId":"u19"},
      "e862163b6c1649b9aa4a331c26cca7cb":{
        "scriptId":"u20"},
      "efd9cc22b1634b98a88cce427449cc61":{
        "scriptId":"u21"},
      "9bbf5a4d8e2c4525ae4cbcef65fbff5e":{
        "scriptId":"u22"},
      "872978ca3bf84ab0abce826289c2c1ea":{
        "scriptId":"u23"},
      "44957ebe00864e8ab23d78c543b3177e":{
        "scriptId":"u24"}},
    "c3ef00bb710240f1adde0de71f5a3adf":{
      "scriptId":"u25"},
    "09a4218518bb421e88ce63f769054786":{
      "scriptId":"u26"},
    "9b5a7ac9262d49be89f5e30a0ce3f0aa":{
      "scriptId":"u27"},
    "8f323f84b9564ee79285e9df27d3bae2":{
      "scriptId":"u28"},
    "0f137130622149c3bc1e567ac73e3f04":{
      "scriptId":"u29"},
    "d84671d9319e4e3eb1241e3d24e9a8ec":{
      "scriptId":"u30"},
    "10e6d8e9297842d09e1e16c0559c33ac":{
      "scriptId":"u31"},
    "4576c985565a40ae9005b8d00dffac15":{
      "scriptId":"u32"},
    "b63209e4b463422885f59a677cf1c75d":{
      "scriptId":"u33"},
    "a03c203ac7b6407c80aa97be61b1a674":{
      "scriptId":"u34"},
    "41dbbc03dcb1464aba0daecca2703f2f":{
      "scriptId":"u35"},
    "4cc5a6bfafd943499cfb4a00bd335334":{
      "scriptId":"u36"},
    "a55584a47d104585a8a7bde591cff85e":{
      "scriptId":"u37"},
    "488d49b7ba66451ebe999a967f509749":{
      "scriptId":"u38"},
    "46bcfef7d60045e2ad046d6e230ff8bb":{
      "scriptId":"u39"},
    "bd518564aceb49e99b6ab852312799a8":{
      "scriptId":"u40"},
    "e13dd54f2e884f05b50392451a76b796":{
      "scriptId":"u41",
      "c73453fa386d40dead74146e04ce954f":{
        "scriptId":"u42"},
      "8878246103114da49b829355f0c5bdae":{
        "scriptId":"u43"},
      "35b1dc1504434f0293e24769738c8e08":{
        "scriptId":"u44"},
      "1f1d119d1ede47d3a712d4b080bbeca8":{
        "scriptId":"u45"},
      "90fa8ef993a6413681691a78c384fde9":{
        "scriptId":"u46"},
      "feb07e2dcb3344d1b08520803a2d24f3":{
        "scriptId":"u47"},
      "626bda77e02f4557abebf86faae7ebc1":{
        "scriptId":"u48"},
      "9ac1e527f59d4a1fb706c277ab155d49":{
        "scriptId":"u49"}},
    "f1e10fe8b8a546899df1ec9fdcd00d01":{
      "scriptId":"u50"},
    "f8f219a7d1684ea99d00fd3f16d891a4":{
      "scriptId":"u51"},
    "b4347f1309f04d118fb300bd1aab8776":{
      "scriptId":"u52"},
    "78773081445d41eab26e1146b67ef745":{
      "scriptId":"u53"},
    "54667adcca4e477d9c7c3ff007dc04fd":{
      "scriptId":"u54"},
    "d59934786296464b90498d06daf1e77e":{
      "scriptId":"u55"},
    "2cd15635d278403495794d9d4dc8b8c1":{
      "scriptId":"u56"},
    "c7fcff5d698e458586632652fd5b23ed":{
      "scriptId":"u57"},
    "f8b7958ac5604b1fbbdb8375c4434649":{
      "scriptId":"u58"},
    "1516162dd0544d7a912798df3433fa44":{
      "scriptId":"u59"},
    "23996fd9d2864551b9d86f4d55ec90ed":{
      "scriptId":"u60"},
    "7bfb016152b04e2895b3358b627f1652":{
      "scriptId":"u61"},
    "6b78d3efa3c442408f88b294aca868dd":{
      "scriptId":"u62"},
    "9ab18b2f70d249b2807855e62e588a7d":{
      "scriptId":"u63"},
    "04817f8209424c4e906c6cc1cde9d2c3":{
      "scriptId":"u64"},
    "c166ea49f7a040b4a9f6db2082589a9a":{
      "scriptId":"u65"},
    "1cef090bc46245e89254e549106bcb92":{
      "scriptId":"u66"},
    "3b4c5209ff4a480495e1f353784b48cf":{
      "scriptId":"u67"},
    "ac92d3c072fd40039f70158a56ead5b1":{
      "scriptId":"u68"},
    "fbee8f14b55747f68e25bb2cdce99400":{
      "scriptId":"u69"},
    "fc22023a915242c78968d1d0c908b59a":{
      "scriptId":"u70"},
    "9786cb3a82f249fa9b94bd073a35d6a3":{
      "scriptId":"u71"},
    "df46fe9eade24127b9b22aa17ca6f5d1":{
      "scriptId":"u72"},
    "fb9bc213aa484f768c0bbda9b3d76265":{
      "scriptId":"u73"},
    "b88b7ede97c24e0cb2d470fafb302ebb":{
      "scriptId":"u74"},
    "1f741ea7487d4ac0ac73f18b18b326dd":{
      "scriptId":"u75"},
    "7d4afcfcdf4a4368969a4d07285a3af4":{
      "scriptId":"u76"},
    "2faa148792a748338fb7b528da7e31eb":{
      "scriptId":"u77"},
    "6bcf32c44e5d4625a554506238e892a7":{
      "scriptId":"u78"},
    "dab0022f1c02448cbb679bf27352bf77":{
      "scriptId":"u79"},
    "47838270e4194f3388eb857a96405425":{
      "scriptId":"u80"},
    "5da46c2ad56148f68f2f4aae5211bcd3":{
      "scriptId":"u81"},
    "cf75190a2e714ecb9e4100ba0892c063":{
      "scriptId":"u82"},
    "48c0c5160fdb40f5978be7b6fdf4ae63":{
      "scriptId":"u83"},
    "bd568100b1ec420eab7e88a021a7af28":{
      "scriptId":"u84"}}});