$axure.loadCurrentPage({
  "url":"article.html",
  "generationDate":new Date(1382378687810.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04ac772c1c8248fdb3719f0b15521fc2",
    "type":"Axure:Page",
    "name":"Article",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d1ba7a69cac048e29e3a652ea4b3c34f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FF2F2F2},
            "location":{
              "x":0,
              "y":111},
            "size":{
              "width":1410,
              "height":869},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e57ee6ebd414b7f9c28e40133a6574c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FF2F2F2},
                "location":{
                  "x":0,
                  "y":111},
                "size":{
                  "width":1410,
                  "height":869},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/article/u0.png"}},
{
          "id":"8ac9fac851734f63b736a2a6240c094c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "lineSpacing":"36px",
            "location":{
              "x":379,
              "y":269},
            "size":{
              "width":629,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47596e85896d4097b4523408eab6b1c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "lineSpacing":"36px",
                "location":{
                  "x":379,
                  "y":269},
                "size":{
                  "width":629,
                  "height":154}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c781db63d6d048bd9d2b7d2fa1d471db",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":28}},
          "adaptiveStyles":{
},
          "masterId":"4003f31f2bf74a6e960c609db1aebe89"},
{
          "id":"e349de97457049309030192cee68c13d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":379,
              "y":440},
            "size":{
              "width":601,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"116da8bdcce6429187a6ad4746cac3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":379,
                  "y":440},
                "size":{
                  "width":601,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b67e09cff14b4c12aa1316ae5c505f88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "lineSpacing":"28px",
            "location":{
              "x":100,
              "y":142},
            "size":{
              "width":161,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa24a4ba2054ef2b89e9b3ac4032cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "lineSpacing":"28px",
                "location":{
                  "x":100,
                  "y":142},
                "size":{
                  "width":161,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33893cb3e94942dcaa3e5080cae61d77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":379,
              "y":1520},
            "size":{
              "width":170,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35249d3a5752449781c25fb2bb5cbf54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":379,
                  "y":1520},
                "size":{
                  "width":170,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf8938380be14c0eb0fd3c151975fe69",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":195},
            "size":{
              "width":1189,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/sections/u29_line.png"}},
{
          "id":"d253d5f6f3a346d3bf954db8e1f775fd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1680},
            "size":{
              "width":601,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news_page/u36_line.png"}},
{
          "id":"b11ec02d143e47258416182030be7f86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1575},
            "size":{
              "width":290,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a6e89007ef4284bee525879d89906b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":1575},
                "size":{
                  "width":290,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u32.png"}},
{
          "id":"183b4c5b9d604ad98a15314616ca3123",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "lineSpacing":"18px",
            "location":{
              "x":379,
              "y":222},
            "size":{
              "width":247,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a81c14f5bb39413fa936a2f9e71c2b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "lineSpacing":"18px",
                "location":{
                  "x":379,
                  "y":222},
                "size":{
                  "width":247,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d22404df5a445c9b8e2326ff33bbbb9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":1500},
            "size":{
              "width":601,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news_page/u36_line.png"}},
{
          "id":"99f82f73527f4b22b6b8eb8112a6ecc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":379,
              "y":611},
            "size":{
              "width":601,
              "height":340},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3178c576067a4f33a16319ad8510dfbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":379,
                  "y":611},
                "size":{
                  "width":601,
                  "height":340},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/article/u38.png"}},
{
          "id":"bfc412ecbcf3431bbe124d899e910fa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":379,
              "y":1007},
            "size":{
              "width":601,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c622acfc62cb47ad86901e5225720a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":379,
                  "y":1007},
                "size":{
                  "width":601,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ab4e9ebaa5f41efb92bfe0b8fa2b96d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":100,
              "y":464},
            "size":{
              "width":210,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdfe87f35d4a4df48e21506a0dfe9a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":100,
                  "y":464},
                "size":{
                  "width":210,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c077cf6ad84741ee8446c8981b4fd545",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":271},
            "size":{
              "width":161,
              "height":159},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"356b5ee810d246ae8ffbc727dd8f3659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":271},
                "size":{
                  "width":161,
                  "height":159},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/partner_profile/u25.png"}},
{
          "id":"b9dc748db71240be8352609d2c41028c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":100,
              "y":498},
            "size":{
              "width":161,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96319632596d47de88b023e3c27a932d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":100,
                  "y":498},
                "size":{
                  "width":161,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa6648af5c144d049b553350627efd06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":333,
              "y":1180},
            "size":{
              "width":114,
              "height":113},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfdf17a9193149058dd98bfb9defc925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":333,
                  "y":1180},
                "size":{
                  "width":114,
                  "height":113},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_page/u50.png"}},
{
          "id":"bbc0124cc14e41adaf99b7299c6fc7eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":477,
              "y":1196},
            "size":{
              "width":531,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"149c33c6cc1842d4a84061f9474d637d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":477,
                  "y":1196},
                "size":{
                  "width":531,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7691d9873f9c4184b83270b03faee3e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":379,
              "y":1330},
            "size":{
              "width":601,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"790d0a67a0ed40c08ef046d487ff22d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":379,
                  "y":1330},
                "size":{
                  "width":601,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e450083d2fdc45af95d8d2efafe88f33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"700",
            "lineSpacing":"18px",
            "location":{
              "x":100,
              "y":220},
            "size":{
              "width":247,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6733521c6064536956140b1216b17aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"700",
                "lineSpacing":"18px",
                "location":{
                  "x":100,
                  "y":220},
                "size":{
                  "width":247,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"997fb24b69c74b52b71234f6f54baf2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":730,
              "y":1524},
            "size":{
              "width":200,
              "height":151}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b342e8956fb4ea6a2cde50039be5b87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":730,
                  "y":1524},
                "size":{
                  "width":200,
                  "height":151}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc9ab20d7f53441882cd9f9f7e07271f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":772,
              "y":1557},
            "size":{
              "width":100,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7bb194287cb40eea86ba711b5e83ba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":772,
                  "y":1557},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u71.png"}},
{
          "id":"fb39455b2ea0463ba50832a7aa91a461",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":790,
              "y":1585},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f743e3d71ff14ff5876f1e732e4911f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":790,
                  "y":1585},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u73.png"}},
{
          "id":"f62459bb29724034a201a712795a654a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":780,
              "y":1613},
            "size":{
              "width":64,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86557964e6ab438e97a5a25364388be8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":780,
                  "y":1613},
                "size":{
                  "width":64,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u75.png"}},
{
          "id":"200b83b938ff4429a6d7beb87d81d10a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":850,
              "y":1613},
            "size":{
              "width":46,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3421e2e796247e48059bd33d63702c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":850,
                  "y":1613},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u77.png"}},
{
          "id":"d7944b1758f749ebb662708806784a07",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1860}},
          "adaptiveStyles":{
},
          "masterId":"922385ae9a2e4795bce54b3d94957db1"},
{
          "id":"f39866cc80d34669aab876ea83652b90",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":620},
            "size":{
              "width":161,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ceec18870c43d78c38f301eb34aa1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":620},
                "size":{
                  "width":161,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/article/u75.png"}},
{
          "id":"486d4f1c86934b9bab1f81f3e017c1e0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":570},
            "size":{
              "width":161,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/article/u77_line.png"}},
{
          "id":"5530eed23e5f4f09b289b381a1286cb8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":179,
              "y":620},
            "size":{
              "width":82,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25f39b92354a424c8e059698035b06d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":179,
                  "y":620},
                "size":{
                  "width":82,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/article/u78.png"}},
{
          "id":"de8a260d5a9a4a46a172dce462370e34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "lineSpacing":"18px",
            "location":{
              "x":111,
              "y":635},
            "size":{
              "width":151,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73126039b7a14e9286ae2365938688a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "lineSpacing":"18px",
                "location":{
                  "x":111,
                  "y":635},
                "size":{
                  "width":151,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08dac78625804a7ab1b41a09655a07e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":100,
              "y":680},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab01386019d945b398190bd10e9b22a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":100,
                  "y":680},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4003f31f2bf74a6e960c609db1aebe89":{
      "packageId":"4003f31f2bf74a6e960c609db1aebe89",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1dbc9764fcbc44e4ad363c2678f1b069",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":849,
                "y":26},
              "size":{
                "width":140,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7abf3b60f2994d22a96b415824ddeb6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":849,
                    "y":26},
                  "size":{
                    "width":140,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u12.png"}},
{
            "id":"25fd79716c9b4affa2bee0a5634583e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":179,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e308b5ba81d4c67aa1834bc5d8e1ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":179,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home_page in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home_page.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"46eb76913c0441ccb9e141066e3539b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":229,
                "y":30},
              "size":{
                "width":120,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8fdd90b2d764b56a50c6b57d0f70899",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":229,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b73211a607964d1e9c4b9b9ca1305b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":386,
                "y":30},
              "size":{
                "width":84,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e7927d5c6e84307adc4e5901413e9fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":386,
                    "y":30},
                  "size":{
                    "width":84,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4799bc506564ee0a2570f1d9758f91a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":611,
                "y":30},
              "size":{
                "width":90,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81434af3de0d4e4dab99e62cf20575b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":611,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Projects in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"projects.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbac75afd9474dbaae2adc57fec2dc75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":728,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17723d194de34772936bdf9bbc9cc1a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":728,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"859e819d30d0424b93da19cf9dfc811f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":875,
                "y":29},
              "size":{
                "width":104,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da35e29e2e9045578f9571b1c098f23e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":875,
                    "y":29},
                  "size":{
                    "width":104,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Join in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"join.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"398bd0a3809546b19482b584abcb2d98",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "lineSpacing":"18px",
              "location":{
                "x":1130,
                "y":37},
              "size":{
                "width":59,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e862163b6c1649b9aa4a331c26cca7cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1130,
                    "y":37},
                  "size":{
                    "width":59,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Subscription in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"subscription.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"efd9cc22b1634b98a88cce427449cc61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "lineSpacing":"18px",
              "location":{
                "x":1013,
                "y":38},
              "size":{
                "width":117,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bbf5a4d8e2c4525ae4cbcef65fbff5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1013,
                    "y":38},
                  "size":{
                    "width":117,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872978ca3bf84ab0abce826289c2c1ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":506,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44957ebe00864e8ab23d78c543b3177e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":506,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "922385ae9a2e4795bce54b3d94957db1":{
      "packageId":"922385ae9a2e4795bce54b3d94957db1",
      "type":"Axure:Master",
      "name":"end",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c73453fa386d40dead74146e04ce954f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7FF2F2F2},
              "size":{
                "width":1410,
                "height":230},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8878246103114da49b829355f0c5bdae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7FF2F2F2},
                  "size":{
                    "width":1410,
                    "height":230},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u3.png"}},
{
            "id":"35b1dc1504434f0293e24769738c8e08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":100,
                "y":111},
              "size":{
                "width":519,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f1d119d1ede47d3a712d4b080bbeca8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":111},
                  "size":{
                    "width":519,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fa8ef993a6413681691a78c384fde9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF949494,
                "opacity":1},
              "location":{
                "x":100,
                "y":40},
              "size":{
                "width":1250,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"feb07e2dcb3344d1b08520803a2d24f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF949494,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":40},
                  "size":{
                    "width":1250,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"626bda77e02f4557abebf86faae7ebc1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":1085,
                "y":111},
              "size":{
                "width":229,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ac1e527f59d4a1fb706c277ab155d49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":111},
                  "size":{
                    "width":229,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "d1ba7a69cac048e29e3a652ea4b3c34f":{
      "scriptId":"u0"},
    "8e57ee6ebd414b7f9c28e40133a6574c":{
      "scriptId":"u1"},
    "8ac9fac851734f63b736a2a6240c094c":{
      "scriptId":"u2"},
    "47596e85896d4097b4523408eab6b1c7":{
      "scriptId":"u3"},
    "c781db63d6d048bd9d2b7d2fa1d471db":{
      "scriptId":"u4",
      "1dbc9764fcbc44e4ad363c2678f1b069":{
        "scriptId":"u5"},
      "7abf3b60f2994d22a96b415824ddeb6a":{
        "scriptId":"u6"},
      "25fd79716c9b4affa2bee0a5634583e3":{
        "scriptId":"u7"},
      "8e308b5ba81d4c67aa1834bc5d8e1ab2":{
        "scriptId":"u8"},
      "46eb76913c0441ccb9e141066e3539b2":{
        "scriptId":"u9"},
      "a8fdd90b2d764b56a50c6b57d0f70899":{
        "scriptId":"u10"},
      "b73211a607964d1e9c4b9b9ca1305b78":{
        "scriptId":"u11"},
      "4e7927d5c6e84307adc4e5901413e9fe":{
        "scriptId":"u12"},
      "e4799bc506564ee0a2570f1d9758f91a":{
        "scriptId":"u13"},
      "81434af3de0d4e4dab99e62cf20575b8":{
        "scriptId":"u14"},
      "dbac75afd9474dbaae2adc57fec2dc75":{
        "scriptId":"u15"},
      "17723d194de34772936bdf9bbc9cc1a9":{
        "scriptId":"u16"},
      "859e819d30d0424b93da19cf9dfc811f":{
        "scriptId":"u17"},
      "da35e29e2e9045578f9571b1c098f23e":{
        "scriptId":"u18"},
      "398bd0a3809546b19482b584abcb2d98":{
        "scriptId":"u19"},
      "e862163b6c1649b9aa4a331c26cca7cb":{
        "scriptId":"u20"},
      "efd9cc22b1634b98a88cce427449cc61":{
        "scriptId":"u21"},
      "9bbf5a4d8e2c4525ae4cbcef65fbff5e":{
        "scriptId":"u22"},
      "872978ca3bf84ab0abce826289c2c1ea":{
        "scriptId":"u23"},
      "44957ebe00864e8ab23d78c543b3177e":{
        "scriptId":"u24"}},
    "e349de97457049309030192cee68c13d":{
      "scriptId":"u25"},
    "116da8bdcce6429187a6ad4746cac3dd":{
      "scriptId":"u26"},
    "b67e09cff14b4c12aa1316ae5c505f88":{
      "scriptId":"u27"},
    "7aa24a4ba2054ef2b89e9b3ac4032cec":{
      "scriptId":"u28"},
    "33893cb3e94942dcaa3e5080cae61d77":{
      "scriptId":"u29"},
    "35249d3a5752449781c25fb2bb5cbf54":{
      "scriptId":"u30"},
    "cf8938380be14c0eb0fd3c151975fe69":{
      "scriptId":"u31"},
    "d253d5f6f3a346d3bf954db8e1f775fd":{
      "scriptId":"u32"},
    "b11ec02d143e47258416182030be7f86":{
      "scriptId":"u33"},
    "21a6e89007ef4284bee525879d89906b":{
      "scriptId":"u34"},
    "183b4c5b9d604ad98a15314616ca3123":{
      "scriptId":"u35"},
    "a81c14f5bb39413fa936a2f9e71c2b6c":{
      "scriptId":"u36"},
    "4d22404df5a445c9b8e2326ff33bbbb9":{
      "scriptId":"u37"},
    "99f82f73527f4b22b6b8eb8112a6ecc9":{
      "scriptId":"u38"},
    "3178c576067a4f33a16319ad8510dfbd":{
      "scriptId":"u39"},
    "bfc412ecbcf3431bbe124d899e910fa1":{
      "scriptId":"u40"},
    "c622acfc62cb47ad86901e5225720a94":{
      "scriptId":"u41"},
    "0ab4e9ebaa5f41efb92bfe0b8fa2b96d":{
      "scriptId":"u42"},
    "cdfe87f35d4a4df48e21506a0dfe9a89":{
      "scriptId":"u43"},
    "c077cf6ad84741ee8446c8981b4fd545":{
      "scriptId":"u44"},
    "356b5ee810d246ae8ffbc727dd8f3659":{
      "scriptId":"u45"},
    "b9dc748db71240be8352609d2c41028c":{
      "scriptId":"u46"},
    "96319632596d47de88b023e3c27a932d":{
      "scriptId":"u47"},
    "aa6648af5c144d049b553350627efd06":{
      "scriptId":"u48"},
    "dfdf17a9193149058dd98bfb9defc925":{
      "scriptId":"u49"},
    "bbc0124cc14e41adaf99b7299c6fc7eb":{
      "scriptId":"u50"},
    "149c33c6cc1842d4a84061f9474d637d":{
      "scriptId":"u51"},
    "7691d9873f9c4184b83270b03faee3e4":{
      "scriptId":"u52"},
    "790d0a67a0ed40c08ef046d487ff22d3":{
      "scriptId":"u53"},
    "e450083d2fdc45af95d8d2efafe88f33":{
      "scriptId":"u54"},
    "a6733521c6064536956140b1216b17aa":{
      "scriptId":"u55"},
    "997fb24b69c74b52b71234f6f54baf2a":{
      "scriptId":"u56"},
    "0b342e8956fb4ea6a2cde50039be5b87":{
      "scriptId":"u57"},
    "bc9ab20d7f53441882cd9f9f7e07271f":{
      "scriptId":"u58"},
    "a7bb194287cb40eea86ba711b5e83ba0":{
      "scriptId":"u59"},
    "fb39455b2ea0463ba50832a7aa91a461":{
      "scriptId":"u60"},
    "f743e3d71ff14ff5876f1e732e4911f1":{
      "scriptId":"u61"},
    "f62459bb29724034a201a712795a654a":{
      "scriptId":"u62"},
    "86557964e6ab438e97a5a25364388be8":{
      "scriptId":"u63"},
    "200b83b938ff4429a6d7beb87d81d10a":{
      "scriptId":"u64"},
    "c3421e2e796247e48059bd33d63702c5":{
      "scriptId":"u65"},
    "d7944b1758f749ebb662708806784a07":{
      "scriptId":"u66",
      "c73453fa386d40dead74146e04ce954f":{
        "scriptId":"u67"},
      "8878246103114da49b829355f0c5bdae":{
        "scriptId":"u68"},
      "35b1dc1504434f0293e24769738c8e08":{
        "scriptId":"u69"},
      "1f1d119d1ede47d3a712d4b080bbeca8":{
        "scriptId":"u70"},
      "90fa8ef993a6413681691a78c384fde9":{
        "scriptId":"u71"},
      "feb07e2dcb3344d1b08520803a2d24f3":{
        "scriptId":"u72"},
      "626bda77e02f4557abebf86faae7ebc1":{
        "scriptId":"u73"},
      "9ac1e527f59d4a1fb706c277ab155d49":{
        "scriptId":"u74"}},
    "f39866cc80d34669aab876ea83652b90":{
      "scriptId":"u75"},
    "e7ceec18870c43d78c38f301eb34aa1e":{
      "scriptId":"u76"},
    "486d4f1c86934b9bab1f81f3e017c1e0":{
      "scriptId":"u77"},
    "5530eed23e5f4f09b289b381a1286cb8":{
      "scriptId":"u78"},
    "25f39b92354a424c8e059698035b06d3":{
      "scriptId":"u79"},
    "de8a260d5a9a4a46a172dce462370e34":{
      "scriptId":"u80"},
    "73126039b7a14e9286ae2365938688a2":{
      "scriptId":"u81"},
    "08dac78625804a7ab1b41a09655a07e2":{
      "scriptId":"u82"},
    "ab01386019d945b398190bd10e9b22a2":{
      "scriptId":"u83"}}});