$axure.loadCurrentPage({
  "url":"contacts.html",
  "generationDate":new Date(1382378689830.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f18a42ea0b984d0fb7dfed679e9e7d73",
    "type":"Axure:Page",
    "name":"Contacts",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"20d89762970f481d8b33def7e585331a",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":111},
            "size":{
              "width":1410,
              "height":559}},
          "adaptiveStyles":{
}},
{
          "id":"6f2fb3e84b8f46c9b2c8defadb549391",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":28}},
          "adaptiveStyles":{
},
          "masterId":"4003f31f2bf74a6e960c609db1aebe89"},
{
          "id":"5a530faa7cb64e83a89c3455d162deaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":938,
              "y":181},
            "size":{
              "width":352,
              "height":406},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adad747c9c014dadbd4caeb05e2da092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":938,
                  "y":181},
                "size":{
                  "width":352,
                  "height":406},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/contacts/u22.png"}},
{
          "id":"54674fa073c9485eb9ea73a81c0a9832",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"25px",
            "location":{
              "x":100,
              "y":727},
            "size":{
              "width":360,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d4f9c57d5b4e6f9f9885df7282bf84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"25px",
                "location":{
                  "x":100,
                  "y":727},
                "size":{
                  "width":360,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"504880f7d2f949b88dd8cadb27eaad83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":959,
              "y":508},
            "size":{
              "width":307,
              "height":55},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"184b0022d4874ab1b96cd1e2f055346c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":959,
                  "y":508},
                "size":{
                  "width":307,
                  "height":55},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/contacts/u26.png"}},
{
          "id":"495bda0f62714e508944a1fb1c36ee06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":958,
              "y":199},
            "size":{
              "width":297,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a158aab12d648e29a1cdad4ddb9cfcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":958,
                  "y":199},
                "size":{
                  "width":297,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8958a1e94ba41148a0946820c59e284",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":959,
              "y":230},
            "size":{
              "width":307,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686ea5e732a842b8b13939a715b5a257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":959,
                  "y":230},
                "size":{
                  "width":307,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d50f362d722e48c3ab585876382595c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":496,
              "y":728},
            "size":{
              "width":504,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7999fcdfa1e44af0bd49f410dfca6dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":496,
                  "y":728},
                "size":{
                  "width":504,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce05a918a3f443c2805d4348528b8891",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":496,
              "y":698},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51d36f831c5d448387453cbade3c4e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":496,
                  "y":698},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40be937ea6024d73a6225acea98f1646",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":100,
              "y":698},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37d34d9a8f4740dd9d655c6f43a56a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":100,
                  "y":698},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce8995ad683743568d902af3f67c3ecd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":959,
              "y":272},
            "size":{
              "width":307,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"b7820577ac2d4e9dab1b9f9f33dccb6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":959,
              "y":318},
            "size":{
              "width":307,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf0c00b82ac4e8e833e6883b4ae05ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":959,
                  "y":318},
                "size":{
                  "width":307,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f558ad04c2c4906a7e8b605c61e6765",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":959,
              "y":360},
            "size":{
              "width":307,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"ca7e393905944614924e37791cbd3d95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":959,
              "y":411},
            "size":{
              "width":307,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9fc4b4bae1e415fa1e1dd61f9f74dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":959,
                  "y":411},
                "size":{
                  "width":307,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03e5d4bb72cb4bee9fa95dbcd74510a7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":959,
              "y":453},
            "size":{
              "width":307,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"1d5fd750eca34b03ad3cf1c3a0c55007",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":740,
              "y":698},
            "size":{
              "width":166,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae56faa609a64c3b929341cebe781f9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":740,
                  "y":698},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53a9529bd6b64e61bc91b8e868385246",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":870}},
          "adaptiveStyles":{
},
          "masterId":"922385ae9a2e4795bce54b3d94957db1"},
{
          "id":"e54e138c857d4b79872f779382898d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":1035,
              "y":520},
            "size":{
              "width":307,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4baef62865a54a41a265ff24ba095b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":1035,
                  "y":520},
                "size":{
                  "width":307,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4003f31f2bf74a6e960c609db1aebe89":{
      "packageId":"4003f31f2bf74a6e960c609db1aebe89",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1dbc9764fcbc44e4ad363c2678f1b069",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":849,
                "y":26},
              "size":{
                "width":140,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7abf3b60f2994d22a96b415824ddeb6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":849,
                    "y":26},
                  "size":{
                    "width":140,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u12.png"}},
{
            "id":"25fd79716c9b4affa2bee0a5634583e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":179,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e308b5ba81d4c67aa1834bc5d8e1ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":179,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home_page in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home_page.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"46eb76913c0441ccb9e141066e3539b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":229,
                "y":30},
              "size":{
                "width":120,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8fdd90b2d764b56a50c6b57d0f70899",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":229,
                    "y":30},
                  "size":{
                    "width":120,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Information in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"information.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b73211a607964d1e9c4b9b9ca1305b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":386,
                "y":30},
              "size":{
                "width":84,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e7927d5c6e84307adc4e5901413e9fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":386,
                    "y":30},
                  "size":{
                    "width":84,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e4799bc506564ee0a2570f1d9758f91a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":611,
                "y":30},
              "size":{
                "width":90,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81434af3de0d4e4dab99e62cf20575b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":611,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Projects in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"projects.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbac75afd9474dbaae2adc57fec2dc75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":728,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17723d194de34772936bdf9bbc9cc1a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":728,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"859e819d30d0424b93da19cf9dfc811f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":875,
                "y":29},
              "size":{
                "width":104,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da35e29e2e9045578f9571b1c098f23e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":875,
                    "y":29},
                  "size":{
                    "width":104,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Join in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"join.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"398bd0a3809546b19482b584abcb2d98",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "horizontalAlignment":"right",
              "lineSpacing":"18px",
              "location":{
                "x":1130,
                "y":37},
              "size":{
                "width":59,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e862163b6c1649b9aa4a331c26cca7cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "horizontalAlignment":"right",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1130,
                    "y":37},
                  "size":{
                    "width":59,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Subscription in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"subscription.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"efd9cc22b1634b98a88cce427449cc61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "lineSpacing":"18px",
              "location":{
                "x":1013,
                "y":38},
              "size":{
                "width":117,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9bbf5a4d8e2c4525ae4cbcef65fbff5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "lineSpacing":"18px",
                  "location":{
                    "x":1013,
                    "y":38},
                  "size":{
                    "width":117,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"872978ca3bf84ab0abce826289c2c1ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "lineSpacing":"28px",
              "location":{
                "x":506,
                "y":30},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44957ebe00864e8ab23d78c543b3177e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "lineSpacing":"28px",
                  "location":{
                    "x":506,
                    "y":30},
                  "size":{
                    "width":90,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Soyze_Service in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"soyze_service.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "922385ae9a2e4795bce54b3d94957db1":{
      "packageId":"922385ae9a2e4795bce54b3d94957db1",
      "type":"Axure:Master",
      "name":"end",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c73453fa386d40dead74146e04ce954f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7FF2F2F2},
              "size":{
                "width":1410,
                "height":230},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8878246103114da49b829355f0c5bdae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7FF2F2F2},
                  "size":{
                    "width":1410,
                    "height":230},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_page/u3.png"}},
{
            "id":"35b1dc1504434f0293e24769738c8e08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":100,
                "y":111},
              "size":{
                "width":519,
                "height":59}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f1d119d1ede47d3a712d4b080bbeca8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":111},
                  "size":{
                    "width":519,
                    "height":59}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fa8ef993a6413681691a78c384fde9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF949494,
                "opacity":1},
              "location":{
                "x":100,
                "y":40},
              "size":{
                "width":1250,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"feb07e2dcb3344d1b08520803a2d24f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF949494,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":40},
                  "size":{
                    "width":1250,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"626bda77e02f4557abebf86faae7ebc1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":1085,
                "y":111},
              "size":{
                "width":229,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ac1e527f59d4a1fb706c277ab155d49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":111},
                  "size":{
                    "width":229,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "20d89762970f481d8b33def7e585331a":{
      "scriptId":"u0"},
    "6f2fb3e84b8f46c9b2c8defadb549391":{
      "scriptId":"u1",
      "1dbc9764fcbc44e4ad363c2678f1b069":{
        "scriptId":"u2"},
      "7abf3b60f2994d22a96b415824ddeb6a":{
        "scriptId":"u3"},
      "25fd79716c9b4affa2bee0a5634583e3":{
        "scriptId":"u4"},
      "8e308b5ba81d4c67aa1834bc5d8e1ab2":{
        "scriptId":"u5"},
      "46eb76913c0441ccb9e141066e3539b2":{
        "scriptId":"u6"},
      "a8fdd90b2d764b56a50c6b57d0f70899":{
        "scriptId":"u7"},
      "b73211a607964d1e9c4b9b9ca1305b78":{
        "scriptId":"u8"},
      "4e7927d5c6e84307adc4e5901413e9fe":{
        "scriptId":"u9"},
      "e4799bc506564ee0a2570f1d9758f91a":{
        "scriptId":"u10"},
      "81434af3de0d4e4dab99e62cf20575b8":{
        "scriptId":"u11"},
      "dbac75afd9474dbaae2adc57fec2dc75":{
        "scriptId":"u12"},
      "17723d194de34772936bdf9bbc9cc1a9":{
        "scriptId":"u13"},
      "859e819d30d0424b93da19cf9dfc811f":{
        "scriptId":"u14"},
      "da35e29e2e9045578f9571b1c098f23e":{
        "scriptId":"u15"},
      "398bd0a3809546b19482b584abcb2d98":{
        "scriptId":"u16"},
      "e862163b6c1649b9aa4a331c26cca7cb":{
        "scriptId":"u17"},
      "efd9cc22b1634b98a88cce427449cc61":{
        "scriptId":"u18"},
      "9bbf5a4d8e2c4525ae4cbcef65fbff5e":{
        "scriptId":"u19"},
      "872978ca3bf84ab0abce826289c2c1ea":{
        "scriptId":"u20"},
      "44957ebe00864e8ab23d78c543b3177e":{
        "scriptId":"u21"}},
    "5a530faa7cb64e83a89c3455d162deaf":{
      "scriptId":"u22"},
    "adad747c9c014dadbd4caeb05e2da092":{
      "scriptId":"u23"},
    "54674fa073c9485eb9ea73a81c0a9832":{
      "scriptId":"u24"},
    "e4d4f9c57d5b4e6f9f9885df7282bf84":{
      "scriptId":"u25"},
    "504880f7d2f949b88dd8cadb27eaad83":{
      "scriptId":"u26"},
    "184b0022d4874ab1b96cd1e2f055346c":{
      "scriptId":"u27"},
    "495bda0f62714e508944a1fb1c36ee06":{
      "scriptId":"u28"},
    "1a158aab12d648e29a1cdad4ddb9cfcf":{
      "scriptId":"u29"},
    "c8958a1e94ba41148a0946820c59e284":{
      "scriptId":"u30"},
    "686ea5e732a842b8b13939a715b5a257":{
      "scriptId":"u31"},
    "d50f362d722e48c3ab585876382595c3":{
      "scriptId":"u32"},
    "7999fcdfa1e44af0bd49f410dfca6dc6":{
      "scriptId":"u33"},
    "ce05a918a3f443c2805d4348528b8891":{
      "scriptId":"u34"},
    "51d36f831c5d448387453cbade3c4e15":{
      "scriptId":"u35"},
    "40be937ea6024d73a6225acea98f1646":{
      "scriptId":"u36"},
    "37d34d9a8f4740dd9d655c6f43a56a18":{
      "scriptId":"u37"},
    "ce8995ad683743568d902af3f67c3ecd":{
      "scriptId":"u38"},
    "b7820577ac2d4e9dab1b9f9f33dccb6b":{
      "scriptId":"u39"},
    "7cf0c00b82ac4e8e833e6883b4ae05ea":{
      "scriptId":"u40"},
    "8f558ad04c2c4906a7e8b605c61e6765":{
      "scriptId":"u41"},
    "ca7e393905944614924e37791cbd3d95":{
      "scriptId":"u42"},
    "f9fc4b4bae1e415fa1e1dd61f9f74dd5":{
      "scriptId":"u43"},
    "03e5d4bb72cb4bee9fa95dbcd74510a7":{
      "scriptId":"u44"},
    "1d5fd750eca34b03ad3cf1c3a0c55007":{
      "scriptId":"u45"},
    "ae56faa609a64c3b929341cebe781f9e":{
      "scriptId":"u46"},
    "53a9529bd6b64e61bc91b8e868385246":{
      "scriptId":"u47",
      "c73453fa386d40dead74146e04ce954f":{
        "scriptId":"u48"},
      "8878246103114da49b829355f0c5bdae":{
        "scriptId":"u49"},
      "35b1dc1504434f0293e24769738c8e08":{
        "scriptId":"u50"},
      "1f1d119d1ede47d3a712d4b080bbeca8":{
        "scriptId":"u51"},
      "90fa8ef993a6413681691a78c384fde9":{
        "scriptId":"u52"},
      "feb07e2dcb3344d1b08520803a2d24f3":{
        "scriptId":"u53"},
      "626bda77e02f4557abebf86faae7ebc1":{
        "scriptId":"u54"},
      "9ac1e527f59d4a1fb706c277ab155d49":{
        "scriptId":"u55"}},
    "e54e138c857d4b79872f779382898d4e":{
      "scriptId":"u56"},
    "4baef62865a54a41a265ff24ba095b6e":{
      "scriptId":"u57"}}});